var _yt_www={};(function(g){var window=this;var baa,caa,Aa,Da,db,kaa,eb,fb,gb,hb,mb,laa,nb,maa,xb,naa,ub,Gb,Xb,$b,dc,fc,Jc,Zc,waa,yaa,xaa,zaa,Aaa,md,pd,Eaa,Faa,Daa,Gaa,be,de,ce,Jaa,Kaa,Laa,Maa,Naa,he,oe,ne,ie,Qaa,ue,re,se,Paa,Be,ke,we,Ae,De,me,fe,ee,ge,ve,xe,Ce,ze,Fe,Te,We,Ze,af,gf,hf,Df,Ef,Waa,Mf,Nf,Xaa,Qf,Uf,Sf,Rf,Yaa,Xf,Yf,ag,cg,dg,eg,hg,gg,jg,fg,kg,Zf,bg,dba,lg,mg,eba,fba,sg,ug,wg,Dg,gba,Ig,Gg,iba,Lg,Jg,Kg,Pg,hba,Ng,lba,kba,jba,Wg,Ug,Xg,Zg,mba,nba,$g,ah,fh,jh,kh,lh,oh,ph,qh,tba,uba,gh,ih,eh,sba,hh,wba,yba,xba,th,uh,vh,oa,aaa;
g.ba=function(a){return function(){return g.aa[a].apply(this,arguments)}};
g.ca=function(a){return void 0!==a};
g.m=function(a,b,c){a=a.split(".");c=c||g.da;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&g.ca(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};
g.p=function(a,b){for(var c=a.split("."),d=b||g.da,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};
g.ea=function(){};
g.fa=function(a){a.getInstance=function(){return a.tc?a.tc:a.tc=new a}};
g.ga=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};
g.ha=function(a){return"array"==g.ga(a)};
g.ia=function(a){var b=g.ga(a);return"array"==b||"object"==b&&"number"==typeof a.length};
g.ja=function(a){return"string"==typeof a};
g.la=function(a){return"number"==typeof a};
g.ma=function(a){return"function"==g.ga(a)};
g.na=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};
g.pa=function(a){return a[oa]||(a[oa]=++aaa)};
baa=function(a,b,c){return a.call.apply(a.bind,arguments)};
caa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};
g.q=function(a,b,c){g.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?baa:caa;return g.q.apply(null,arguments)};
g.r=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};
g.t=function(a,b){function c(){}
c.prototype=b.prototype;a.L=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.bV=function(a,c,f){for(var k=Array(arguments.length-2),l=2;l<arguments.length;l++)k[l-2]=arguments[l];return b.prototype[c].apply(a,k)}};
g.qa=function(a){g.qa[" "](a);return a};
g.ra=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,g.ra);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};
g.sa=function(a,b){return 0==a.lastIndexOf(b,0)};
g.ta=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};
g.ua=function(a){return(0,window.encodeURIComponent)(String(a))};
g.va=function(a){return(0,window.decodeURIComponent)(a.replace(/\+/g," "))};
g.wa=function(a){if(!daa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(eaa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(faa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(gaa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(haa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(iaa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(jaa,"&#0;"));return a};
g.xa=function(a,b){return-1!=a.indexOf(b)};
g.ya=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
g.Ba=function(a,b){for(var c=0,d=(0,g.za)(String(a)).split("."),e=(0,g.za)(String(b)).split("."),f=Math.max(d.length,e.length),k=0;0==c&&k<f;k++){var l=d[k]||"",n=e[k]||"",u=RegExp("(\\d*)(\\D*)","g"),w=RegExp("(\\d*)(\\D*)","g");do{var G=u.exec(l)||["","",""],S=w.exec(n)||["","",""];if(0==G[0].length&&0==S[0].length)break;c=Aa(0==G[1].length?0:(0,window.parseInt)(G[1],10),0==S[1].length?0:(0,window.parseInt)(S[1],10))||Aa(0==G[2].length,0==S[2].length)||Aa(G[2],S[2])}while(0==c)}return c};
Aa=function(a,b){return a<b?-1:a>b?1:0};
g.Ca=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c)>>>0;return b};
Da=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};
g.Fa=function(a){var b=g.ja(void 0)?g.ya(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};
g.Ha=function(a,b,c){b=g.Ga(a,b,c);return 0>b?null:g.ja(a)?a.charAt(b):a[b]};
g.Ga=function(a,b,c){for(var d=a.length,e=g.ja(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};
g.Ja=function(a,b){return 0<=(0,g.Ia)(a,b)};
g.La=function(a,b){var c=(0,g.Ia)(a,b),d;(d=0<=c)&&g.Ka(a,c);return d};
g.Ka=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};
g.Ma=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
g.Oa=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(g.ia(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var k=0;k<f;k++)a[e+k]=d[k]}else a.push(d)}};
g.Pa=function(a){return function(){return a}};
g.Qa=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};
g.Ra=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};
g.Sa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};
g.Ta=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};
g.Ua=function(a){for(var b in a)return!1;return!0};
g.Va=function(a,b){b in a&&delete a[b]};
g.Wa=function(a,b,c){if(null!==a&&b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};
g.Xa=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
g.Za=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ya.length;f++)c=Ya[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
g.ab=function(a){return g.xa(g.$a,a)};
g.bb=function(){return g.ab("Trident")||g.ab("MSIE")};
g.cb=function(){return(g.ab("Chrome")||g.ab("CriOS"))&&!g.ab("Edge")};
db=function(a){g.da.setTimeout(function(){throw a;},0)};
kaa=function(){var a=g.da.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!g.ab("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,g.q)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);
b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});
if("undefined"!==typeof a&&!g.bb()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(g.ca(c.next)){c=c.next;var a=c.Dp;c.Dp=null;a()}};
return function(a){d.next={Dp:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};
window.document.documentElement.appendChild(b)}:function(a){g.da.setTimeout(a,0)}};
eb=function(a,b,c){this.F=c;this.B=a;this.D=b;this.C=0;this.A=null};
fb=function(a,b){a.D(b);a.C<a.F&&(a.C++,b.next=a.A,a.A=b)};
gb=function(){this.C=this.A=null};
hb=function(){this.next=this.scope=this.oe=null};
mb=function(a,b){ib||laa();jb||(ib(),jb=!0);var c=kb,d=lb.get();d.set(a,b);c.C?c.C.next=d:c.A=d;c.C=d};
laa=function(){if(g.da.Promise&&g.da.Promise.resolve){var a=g.da.Promise.resolve(void 0);ib=function(){a.then(nb)}}else ib=function(){var a=nb;
!g.ma(g.da.setImmediate)||g.da.Window&&g.da.Window.prototype&&!g.ab("Edge")&&g.da.Window.prototype.setImmediate==g.da.setImmediate?(ob||(ob=kaa()),ob(a)):g.da.setImmediate(a)}};
nb=function(){for(var a;a=kb.remove();){try{a.oe.call(a.scope)}catch(b){db(b)}fb(lb,a)}jb=!1};
g.pb=function(){this.Md=this.Md;this.Jb=this.Jb};
g.sb=function(a,b){g.qb(a,g.r(g.rb,b))};
g.qb=function(a,b){a.Md?b.call(void 0):(a.Jb||(a.Jb=[]),a.Jb.push(g.ca(void 0)?(0,g.q)(b,void 0):b))};
g.rb=function(a){a&&"function"==typeof a.dispose&&a.dispose()};
g.tb=function(a){g.pb.call(this);this.D=1;this.C=[];this.B=0;this.A=[];this.sd={};this.F=!!a};
maa=function(a,b,c){mb(function(){a.apply(b,c)})};
g.wb=function(a){ub(g.vb,arguments)};
g.v=function(a,b){return a in g.vb?g.vb[a]:b};
g.yb=function(a,b){g.ma(a)&&(a=xb(a));return window.setTimeout(a,b)};
g.zb=function(a,b){g.ma(a)&&(a=xb(a));return window.setInterval(a,b)};
g.Ab=function(a){window.clearTimeout(a)};
g.Bb=function(a){window.clearInterval(a)};
xb=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw g.Cb(b),b;}}:a};
g.Cb=function(a,b,c,d,e){var f=g.p("yt.logging.errors.log");f?f(a,b,c,d,e):(f=g.v("ERRORS",[]),f.push([a,b,c,d,e]),g.wb("ERRORS",f))};
naa=function(a,b,c,d,e){var f=!1;if(g.vb.Qo&&g.vb.Qo.log_window_onerror_fraction&&Math.random()<g.vb.Qo.log_window_onerror_fraction)f=!0;else for(var k=window.document.getElementsByTagName("script"),l=0,n=k.length;l<n;l++)if(0<k[l].src.indexOf("/debug-")){f=!0;break}f&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),g.Cb(e))};
g.Eb=function(a){return a in g.Db};
g.Fb=function(a,b,c){var d=b||{};if(a=a in g.Db?g.Db[a]:c)for(var e in d)a=a.replace(new RegExp("\\$"+e,"gi"),function(){return d[e]});
return a};
ub=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};
g.x=function(a,b,c){var d=Gb();if(d){var e=d.subscribe(a,function(){if(!Hb||Hb!=e){var d=arguments,k;k=function(){Ib[e]&&b.apply(c||window,d)};
try{Jb[a]?k():g.yb(k,0)}catch(l){g.Cb(l)}}},c);
Ib[e]=!0;Kb[a]||(Kb[a]=[]);Kb[a].push(e);return e}return 0};
g.Lb=function(a){var b=Gb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,g.y)(a,function(a){b.unsubscribeByKey(a);delete Ib[a]}))};
g.z=function(a,b){var c=Gb();return c?c.publish.apply(c,arguments):!1};
g.Mb=function(a,b){Jb[a]=!0;var c=Gb(),c=c?c.publish.apply(c,arguments):!1;Jb[a]=!1;return c};
Gb=function(){return g.p("yt.pubsub.instance_")};
g.Nb=function(){return!!g.p("yt.scheduler.instance")};
g.Ob=function(a,b){(0,window.isNaN)(b)&&(b=void 0);var c=g.p("yt.scheduler.instance.addJob");return c?c(a,1,b):void 0===b?(a(),window.NaN):g.yb(a,b||0)};
g.Pb=function(a,b){return g.Ob(a,b)};
g.Qb=function(a){if(!(0,window.isNaN)(a)){var b=g.p("yt.scheduler.instance.cancelJob");b?b(a):g.Ab(a)}};
g.Sb=function(a){for(var b=0,c=a.length;b<c;b++)g.Qb(a[b])};
g.Tb=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.G=d?xb(d):null;this.F=e?xb(e):null;this.D=[];this.A=this.C=0};
g.Ub=function(a){g.Qb(a.C);a.C=g.Pb((0,g.q)(a.init,a))};
g.Yb=function(a){a.name in Vb&&Xb(a.name);Vb[a.name]={reqs:[],disable:(0,g.q)(a.disable,a)};(0,g.y)(a.deps,function(b){if(!(b in Vb))throw Error("Module "+b+" required by "+a.name);Vb[b].reqs.push(a.name)});
a.enable()};
Xb=function(a){if(a in Vb){var b=Vb[a];(0,g.y)(b.reqs,function(a){Xb(a)});
try{b.disable()}catch(c){}delete Vb[a]}};
$b=function(){this.A="";this.C=Zb};
g.ac=function(a){return a instanceof $b&&a.constructor===$b&&a.C===Zb?a.A:"type_error:Const"};
g.bc=function(a){var b=new $b;b.A=a;return b};
dc=function(){this.A="";this.C=cc};
g.ec=function(a){if(a instanceof dc&&a.constructor===dc&&a.C===cc)return a.A;g.ga(a);return"type_error:SafeStyle"};
fc=function(a){var b=new dc;b.A=a;return b};
g.gc=function(a){var b="",c;for(c in a){if(!/^[-_a-zA-Z0-9]+$/.test(c))throw Error("Name allows only [-_a-zA-Z0-9], got: "+c);var d=a[c];if(null!=d){if(d instanceof $b)d=g.ac(d);else if(oaa.test(d)){for(var e=!0,f=!0,k=0;k<d.length;k++){var l=d.charAt(k);"'"==l&&f?e=!e:'"'==l&&e&&(f=!f)}e&&f||(d="zClosurez")}else d="zClosurez";b+=c+":"+d+";"}}return b?fc(b):paa};
g.ic=function(){this.A="";this.C=hc};
g.jc=function(a){if(a instanceof g.ic&&a.constructor===g.ic&&a.C===hc)return a.A;g.ga(a);return"type_error:SafeUrl"};
g.lc=function(a){if(a instanceof g.ic)return a;a=a.Pf?a.Oe():String(a);qaa.test(a)||(a="about:invalid#zClosurez");return g.kc(a)};
g.kc=function(a){var b=new g.ic;b.A=a;return b};
g.nc=function(){this.A="";this.C=mc};
g.oc=function(a){if(a instanceof g.nc&&a.constructor===g.nc&&a.C===mc)return a.A;g.ga(a);return"type_error:TrustedResourceUrl"};
g.qc=function(){this.A="";this.B=pc;this.C=null};
g.rc=function(a){if(a instanceof g.qc&&a.constructor===g.qc&&a.B===pc)return a.A;g.ga(a);return"type_error:SafeHtml"};
g.tc=function(a){if(a instanceof g.qc)return a;var b=null;a.um&&(b=a.zg());a=g.wa(a.Pf?a.Oe():String(a));return g.sc(a,b)};
g.wc=function(a,b,c){if(!uc.test(a))throw Error("Invalid tag name <"+a+">.");if(a.toUpperCase()in raa)throw Error("Tag name <"+a+"> is not allowed for SafeHtml.");return g.vc(a,b,c)};
g.xc=function(a){function b(a){g.ha(a)?(0,g.y)(a,b):(a=g.tc(a),d+=g.rc(a),a=a.zg(),0==c?c=a:0!=a&&c!=a&&(c=null))}
var c=0,d="";(0,g.y)(arguments,b);return g.sc(d,c)};
g.sc=function(a,b){var c=new g.qc;c.A=a;c.C=b;return c};
g.vc=function(a,b,c){var d=null,e,f="";if(b)for(e in b){if(!uc.test(e))throw Error('Invalid attribute name "'+e+'".');var k=b[e];if(null!=k){var l,n=a;l=e;if(k instanceof $b)k=g.ac(k);else if("style"==l.toLowerCase()){if(!g.na(k))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof k+" given: "+k);k instanceof dc||(k=g.gc(k));k=g.ec(k)}else{if(/^on/i.test(l))throw Error('Attribute "'+l+'" requires goog.string.Const value, "'+k+'" given.');if(l.toLowerCase()in
saa)if(k instanceof g.nc)k=g.oc(k);else if(k instanceof g.ic)k=g.jc(k);else if(g.ja(k))k=g.lc(k).Oe();else throw Error('Attribute "'+l+'" on tag "'+n+'" requires goog.html.SafeUrl, goog.string.Const, or string, value "'+k+'" given.');}k.Pf&&(k=k.Oe());l=l+'="'+g.wa(String(k))+'"';f+=" "+l}}e="<"+a+f;null!=c?g.ha(c)||(c=[c]):c=[];!0===taa[a.toLowerCase()]?e+=">":(d=g.xc(c),e+=">"+g.rc(d)+"</"+a+">",d=d.zg());(a=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(a)?d=0:d=null);return g.sc(e,d)};
g.yc=function(a,b){a.innerHTML=g.rc(b)};
g.zc=function(a,b){var c;c=b instanceof g.ic?b:g.lc(b);a.href=g.jc(c)};
g.A=function(a,b){return a?a.dataset?a.dataset[g.Ac(b)]:a.getAttribute("data-"+b):null};
g.Bc=function(a,b){return a?a.dataset?g.Ac(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};
g.Ac=function(a){return Cc[a]||(Cc[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};
g.Ec=function(a,b){var c=g.Dc(a);window.spf.script.load(a,c,b)};
g.Fc=function(a,b){var c=g.Dc(a);window.spf.script.ignore(c,b)};
g.Dc=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(uaa,""),b=b.replace(vaa,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};
g.Gc=function(a){return g.v("EXPERIMENT_FLAGS",{})[a]};
g.Hc=function(a,b){g.ac(a);g.ac(a);return g.sc(b,null)};
g.Ic=function(){return g.ab("iPhone")&&!g.ab("iPod")&&!g.ab("iPad")};
Jc=function(){var a=g.da.document;return a?a.documentMode:void 0};
g.Mc=function(a){return Kc[a]||(Kc[a]=0<=g.Ba(g.Lc,a))};
g.Oc=function(a){return Number(g.Nc)>=a};
g.Pc=function(a){return eval("("+a+")")};
g.Qc=function(a,b,c,d,e,f,k){var l="";a&&(l+=a+":");c&&(l+="//",b&&(l+=b+"@"),l+=c,d&&(l+=":"+d));e&&(l+=e);f&&(l+="?"+f);k&&(l+="#"+k);return l};
g.Rc=function(a){return a?(0,window.decodeURI)(a):a};
g.Tc=function(a,b){return b.match(g.Sc)[a]||null};
g.Uc=function(a){return g.Rc(g.Tc(3,a))};
g.Vc=function(a){a=a.match(g.Sc);return g.Qc(null,null,null,null,a[5],a[6],a[7])};
g.Wc=function(a){var b=a.indexOf("#");return 0>b?a:a.substr(0,b)};
g.Xc=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
g.Yc=function(a,b,c){if(g.ha(b))for(var d=0;d<b.length;d++)g.Yc(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",g.ua(b))};
Zc=function(a,b){for(var c in b)g.Yc(c,b[c],a);return a};
g.$c=function(a){a=Zc([],a);a[0]="";return a.join("")};
g.ad=function(a,b){return g.Xc(Zc([a],b))};
g.bd=function(a){"?"==a.charAt(0)&&(a=a.substr(1));a=a.split("&");for(var b={},c=0,d=a.length;c<d;c++){var e=a[c].split("=");if(1==e.length&&e[0]||2==e.length){var f=g.va(e[0]||""),e=g.va(e[1]||"");f in b?g.ha(b[f])?g.Oa(b[f],e):b[f]=[b[f],e]:b[f]=e}}return b};
g.cd=function(a,b){var c,d=b||{},e=a.split("#",2);c=e[0];var e=1<e.length?"#"+e[1]:"",f=c.split("?",2);c=f[0];var f=g.bd(f[1]||""),k;for(k in d)f[k]=d[k];return g.ad(c,f)+e};
waa=function(a){a=g.dd(a);return g.ed(a)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};
g.ed=function(a){return null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1};
g.dd=function(a){a=g.Uc(a);return null===a?null:a.split(".").reverse()};
g.fd=function(a){return a&&"status"in a?a.status:-1};
g.gd=function(a){switch(g.fd(a)){case 200:case 201:case 202:case 203:case 204:case 205:case 206:case 304:return!0;default:return!1}};
yaa=function(a,b,c,d,e,f,k){function l(){4==(n&&"readyState"in n?n.readyState:0)&&b&&xb(b)(n)}
var n=hd&&hd();if(!("open"in n))return null;"onloadend"in n?n.addEventListener("loadend",l,!1):n.onreadystatechange=l;c=(c||"GET").toUpperCase();d=d||"";n.open(c,a,!0);f&&(n.responseType=f);k&&(n.withCredentials=!0);f="POST"==c;if(e=xaa(a,e))for(var u in e)n.setRequestHeader(u,e[u]),"content-type"==u.toLowerCase()&&(f=!1);f&&n.setRequestHeader("Content-Type","application/x-www-form-urlencoded");n.send(d);return n};
xaa=function(a,b){b=b||{};var c;c||(c=window.location.href);var d=g.Tc(1,a),e=g.Uc(a);d&&e?(d=c,c=a.match(g.Sc),d=d.match(g.Sc),c=c[3]==d[3]&&c[1]==d[1]&&c[4]==d[4]):c=e?g.Uc(c)==e&&(Number(g.Tc(4,c))||null)==(Number(g.Tc(4,a))||null):!0;for(var f in id){if((e=d=g.v(id[f]))&&!(e=c)){var e=f,k=g.v("CORS_HEADER_WHITELIST")||{},l=g.Uc(a);e=l?(k=k[l])?g.Ja(k,e):!1:!0}e&&(b[f]=d)}return b};
g.jd=function(a,b){b.method="POST";b.ba||(b.ba={});return g.B(a,b)};
zaa=function(a,b){var c=g.v("XSRF_FIELD_NAME",void 0),d;b.headers&&(d=b.headers["Content-Type"]);return!b.Wy&&(!g.Uc(a)||b.withCredentials||g.Uc(a)==window.document.location.hostname)&&"POST"==b.method&&(!d||"application/x-www-form-urlencoded"==d)&&!(b.ba&&b.ba[c])};
g.B=function(a,b){var c=b.format||"JSON";b.RD&&(a=window.document.location.protocol+"//"+window.document.location.hostname+(window.document.location.port?":"+window.document.location.port:"")+a);var d=g.v("XSRF_FIELD_NAME",void 0),e=g.v("XSRF_TOKEN",void 0),f=b.ia;f&&(f[d]&&delete f[d],a=g.cd(a,f));var k=b.postBody||"",f=b.ba;zaa(a,b)&&(f||(f={}),f[d]=e);f&&g.ja(k)&&(d=g.bd(k),g.Za(d,f),k=b.Du&&"JSON"==b.Du?JSON.stringify(d):g.$c(d));var l=!1,n,u=yaa(a,function(a){if(!l){l=!0;n&&g.Ab(n);var d=g.gd(a),
e=null;if(d||400<=a.status&&500>a.status)e=Aaa(c,a,b.qb);if(d)a:{switch(c){case "XML":d=0==(0,window.parseInt)(e&&e.return_code,10);break a;case "RAW":d=!0;break a}d=!!e}var e=e||{},f=b.context||g.da;d?b.X&&b.X.call(f,a,e):b.onError&&b.onError.call(f,a,e);b.Xa&&b.Xa.call(f,a,e)}},b.method,k,b.headers,b.responseType,b.withCredentials);
b.Cc&&0<b.timeout&&(n=g.yb(function(){l||(l=!0,u.abort(),g.Ab(n),b.Cc.call(b.context||g.da,u))},b.timeout));
return u};
Aaa=function(a,b,c){var d=null;switch(a){case "JSON":a=b.responseText;b=b.getResponseHeader("Content-Type")||"";a&&0<=b.indexOf("json")&&(d=g.Pc(a));break;case "XML":if(b=(b=b.responseXML)?g.kd(b):null)d={},(0,g.y)(b.getElementsByTagName("*"),function(a){d[a.tagName]=g.ld(a)})}c&&md(d);
return d};
md=function(a){if(g.na(a))for(var b in a)"html_content"==b||g.ta(b,"_html")?a[b]=g.Hc(g.bc("HTML that is escaped and sanitized server-side and passed through yt.net.ajax"),a[b]):md(a[b])};
g.kd=function(a){return a?(a=("responseXML"in a?a.responseXML:a).getElementsByTagName("root"))&&0<a.length?a[0]:null:null};
g.ld=function(a){var b="";(0,g.y)(a.childNodes,function(a){b+=a.nodeValue});
return b};
g.nd=function(){return{apiaryHost:g.v("APIARY_HOST",void 0),Xx:g.v("APIARY_HOST_FIRSTPARTY",void 0),gapiHintOverride:g.v("GAPI_HINT_OVERRIDE"),gapiHintParams:g.v("GAPI_HINT_PARAMS",void 0),innertubeApiKey:g.v("INNERTUBE_API_KEY",void 0),innertubeApiVersion:g.v("INNERTUBE_API_VERSION",void 0),TD:g.v("INNERTUBE_CONTEXT_CLIENT_NAME","WEB"),innertubeContextClientVersion:g.v("INNERTUBE_CONTEXT_CLIENT_VERSION",void 0),VD:g.v("INNERTUBE_CONTEXT_HL",void 0),UD:g.v("INNERTUBE_CONTEXT_GL",void 0),YO:g.v("XHR_APIARY_HOST",
void 0)}};
g.od=function(a){a={client:{hl:a.VD,gl:a.UD,clientName:a.TD,clientVersion:a.innertubeContextClientVersion}};g.v("DELEGATED_SESSION_ID")&&(a.user={onBehalfOfUser:g.v("DELEGATED_SESSION_ID")});return a};
pd=function(){this.A=g.nd()};
g.qd=function(a,b,c){this.A=a;this.B=b;this.C=c};
g.vd=function(a,b){g.rd[a.endpoint]=g.rd[a.endpoint]||[];var c=g.rd[a.endpoint];c.push(a.Bb);sd[a.endpoint]=b;20<=c.length?g.td():g.ud()};
g.td=function(){g.Ab(g.wd);if(!g.Ua(g.rd)){for(var a in g.rd){var b=g.xd[a];if(!b){b=sd[a];if(!b)continue;b=new b;g.xd[a]=b}var c=b.C();c.requestTimeMs=Math.round((0,g.yd)());c[Baa[a]]=g.rd[a];b.B(a,c,{});delete g.rd[a]}g.Ua(g.rd)||g.ud()}};
g.ud=function(){g.Ab(g.wd);g.wd=g.yb(g.td,g.v("VISIBILITY_TIMEOUT",1E4))};
g.zd=function(a,b,c,d){var e={};e.eventTimeMs=Math.round(d||(0,g.yd)());e[a]=b;g.vd({endpoint:"log_event",Bb:e},c)};
g.Ad=function(){var a=g.v("client-screen-nonce",void 0);a||(a=g.v("EVENT_ID",void 0));return a};
g.Bd=function(a,b){this.x=g.ca(a)?a:0;this.y=g.ca(b)?b:0};
g.Cd=function(a,b){this.width=a;this.height=b};
g.C=function(a){return g.ja(a)?window.document.getElementById(a):a};
g.Dd=function(a){return g.ja(a)?window.document.getElementById(a):a};
g.D=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=g.Ed(window.document,"*",a,b)[0];return d||null};
g.Ed=function(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,k;k=a[f];f++)b==k.nodeName&&(d[e++]=k);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;k=a[f];f++)b=k.className,"function"==typeof b.split&&g.Ja(b.split(/\s+/),c)&&(d[e++]=k);d.length=e;return d}return a};
g.Gd=function(a,b){g.Ra(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Fd.hasOwnProperty(d)?a.setAttribute(Fd[d],b):g.sa(d,"aria-")||g.sa(d,"data-")?a.setAttribute(d,b):a[d]=b})};
g.Id=function(a){return g.Hd(a||window)};
g.Hd=function(a){a=a.document;a=g.Jd(a)?a.documentElement:a.body;return new g.Cd(a.clientWidth,a.clientHeight)};
g.Ld=function(a){var b=g.Kd(a);a=a.parentWindow||a.defaultView;return g.E&&g.Mc("10")&&a.pageYOffset!=b.scrollTop?new g.Bd(b.scrollLeft,b.scrollTop):new g.Bd(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};
g.Kd=function(a){return a.scrollingElement?a.scrollingElement:!g.Md&&g.Jd(a)?a.documentElement:a.body||a.documentElement};
g.Od=function(a,b,c){return g.Nd(window.document,arguments)};
g.Nd=function(a,b){var c=b[0],d=b[1];if(!Caa&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',g.wa(d.name),'"');if(d.type){c.push(' type="',g.wa(d.type),'"');var e={};g.Za(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(g.ja(d)?c.className=d:g.ha(d)?c.className=d.join(" "):g.Gd(c,d));2<b.length&&g.Pd(a,c,b,2);return c};
g.Pd=function(a,b,c,d){function e(c){c&&b.appendChild(g.ja(c)?a.createTextNode(c):c)}
for(;d<c.length;d++){var f=c[d];!g.ia(f)||g.na(f)&&0<f.nodeType?e(f):(0,g.y)(Daa(f)?g.Ma(f):f,e)}};
g.Jd=function(a){return"CSS1Compat"==a.compatMode};
g.Qd=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};
g.Rd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};
g.Sd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};
Eaa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
Faa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};
g.Td=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
Daa=function(a){if(a&&"number"==typeof a.length){if(g.na(a))return"function"==typeof a.item||"string"==typeof a.item;if(g.ma(a))return"function"==typeof a.item}return!1};
g.Ud=function(a,b,c,d){c||(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null};
g.Vd=function(a,b,c){a&&(c&&(c=g.$a,c=!(c&&0<=c.toLowerCase().indexOf("cobalt"))),c?a&&(a=g.Od("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),g.Td(a).body.appendChild(a)):Gaa(a,b))};
g.Wd=function(a){try{window.navigator&&window.navigator.sendBeacon&&window.navigator.sendBeacon(a,"")||g.Vd(a,void 0)}catch(b){g.Vd(a,void 0)}};
Gaa=function(a,b){var c=new window.Image,d=""+Haa++;Xd[d]=c;c.onload=c.onerror=function(){b&&Xd[d]&&b();delete Xd[d]};
c.src=a};
g.Yd=function(a,b){this.version=a;this.args=b};
g.Zd=function(a,b){this.topic=a;this.vf=b};
g.ae=function(a,b){var c=g.$d();return c?c.publish.call(c,a.toString(),a,b):!1};
g.$d=function(){return g.p("yt.pubsub2.instance_")};
be=function(a){g.Yd.call(this,1,arguments)};
de=function(a){var b=a||window;if(!(b.performance&&b.performance.timing&&b.performance.getEntriesByType))return{Ek:0,Zv:0};a=g.Id(b);for(var c=[],d=b.document.getElementsByTagName("*"),e=0,f=d.length;e<f;e++){var k=d[e];if("IMG"==k.tagName||"IFRAME"==k.tagName){var l=ce(k,k.src,a);if(l){if("IFRAME"==k.tagName){var n;try{n=de(k.contentWindow).Ek}catch(u){n=0}0<n&&(l.timing=n)}c.push(l)}}(l=b.getComputedStyle(k)["background-image"])&&(l=Iaa.exec(l))&&1<l.length&&(l=ce(k,l[1],a))&&c.push(l)}n=b.performance.getEntriesByType("resource");
k=b.performance.getEntriesByType("mark");d={};e=0;for(f=n.length;e<f;e++)l=n[e],d[l.name]=l.responseEnd;e=0;for(f=k.length;e<f;e++)l=k[e],"mark_iframe_loaded: "==l.name.slice(0,20)&&(d[l.name.slice(20)]=l.startTime);e=0;for(f=c.length;e<f;e++)k=c[e],k.timing||(k.timing=d[k.url]||0);b=Jaa(b,n);a=Kaa(b,a,c);k=c=0;if(a.length)for(d=n=0,e=a.length;d<e;d++)f=a[d],k=f.timing-k,0<k&&1>n&&(c+=(1-n)*k),k=f.timing,n=f.progress;return{Ek:Math.round(c||b),Zv:k}};
ce=function(a,b,c){if(b&&a.getBoundingClientRect){var d=a.getBoundingClientRect();a=Math.max(d.top,0);var e=Math.min(d.right,c.width);c=Math.min(d.bottom,c.height);d=Math.max(d.left,0);if(c>a&&e>d)return new Laa(a,e,c,d,b)}return null};
Jaa=function(a,b){var c,d=a.performance.timing.navigationStart;if("msFirstPaint"in a.performance.timing)c=a.performance.timing.A-d;else if("chrome"in a&&"loadTimes"in a.chrome){var e=a.chrome.loadTimes(),f=e.firstPaintTime;if(0<f){var k=e.startLoadTime;"requestTime"in e&&(k=e.requestTime);f>=k&&(c=1E3*(f-k))}}if(void 0===c||0>c||12E4<c){c=a.performance.timing.responseStart-d;for(var l={},d=a.document.getElementsByTagName("head")[0].children,e=0,f=d.length;e<f;e++)k=d[e],"SCRIPT"==k.tagName&&k.src&&
!k.async?l[k.src]=!0:"LINK"==k.tagName&&"stylesheet"==k.rel&&k.href&&(l[k.href]=!0);b.some(function(a){if(!l[a.name]||"script"!=a.initiatorType&&"link"!=a.initiatorType)return!0;a=a.responseEnd;if(void 0===c||a>c)c=a})}return Math.max(c,0)||0};
Kaa=function(a,b,c){for(var d={0:0},e=0,f=0,k=c.length;f<k;f++){var l=c[f],n=a;l.timing>a&&(n=l.timing);d[n]||(d[n]=0);l=(l.A-l.D)*(l.B-l.C);d[n]+=l;e+=l}f=b.width*b.height;0<f&&(f=.1*Math.max(f-e,0),a in d||(d[a]=0),d[a]+=f,e+=f);a=[];if(e){for(var u in d)b=new Maa((0,window.parseFloat)(u),d[u]),a.push(b);a.sort(function(a,b){return a.timing-b.timing});
f=d=0;for(k=a.length;f<k;f++)b=a[f],d+=b.ul,b.progress=d/e}return a};
Laa=function(a,b,c,d,e){this.A=c;this.C=d;this.B=b;this.D=a;this.url=e};
Maa=function(a,b){this.ul=b;this.timing=a};
Naa=function(){if("cold"==ee().yt_lt){var a=fe(),b=ge(),c;for(c in a)"tick_"+c in b||he(c,a[c]);a=ee();for(c in a)"info_"+c in b||ie(c,a[c])}};
g.le=function(a,b,c){b||"_"==a[0]||je(a);var d=fe(c);d[a]=b||(0,g.yd)();he(a,b,c)||ke(!1,c);return d[a]};
he=function(a,b,c){ge(c)["tick_"+a]=b;return g.Gc("csi_on_gel")?(c=me(c),"_start"==a?g.zd("latencyActionBaselined",{clientActionNonce:c},pd,b):g.zd("latencyActionTicked",{tickName:a,clientActionNonce:c},pd,b),!0):!1};
oe=function(a,b){ne("yt_sts",a,void 0);g.le("_start",b,void 0)};
ne=function(a,b,c){ee(c)[a]=b;ie(a,b,c)};
ie=function(a,b,c){ge(c)["info_"+a]=b;if(g.Gc("csi_on_gel"))if(a in pe){var d={};a=pe[a];a in Oaa&&(b=!!b);d[a]=b;b=me(c);d.clientActionNonce=b;g.zd("latencyActionInfo",d,pd)}else g.Cb(Error("Unknown label "+a+" logged with GEL CSI."))};
Qaa=function(){var a=g.v("TIMING_INFO",{}),b;for(b in a)ne(b,a[b]);(a=g.Ad())&&ne("csn",a);(a=g.v("PREVIOUS_ACTION",void 0))&&ne("pa",a);a=ee();a.p=g.v("CLIENT_PROTOCOL")||"unknown";a.t=g.v("CLIENT_TRANSPORT")||"unknown";qe.now&&qe.timing?(a=qe.timing.navigationStart+qe.now(),a=Math.round((0,g.F)()-a)):a=null;null!=a&&ne("yt_hrd",a);window.navigator&&window.navigator.sendBeacon&&ne("ba",1);if("cold"==ee().yt_lt){a=qe.timing||{};a:if(a.msFirstPaint)b=Math.max(0,a.msFirstPaint);else{if(b=window.chrome)if(b=
b.loadTimes,g.ma(b)){b=b();var c=1E3*Math.min(b.requestTime||window.Infinity,b.startLoadTime||window.Infinity),c=window.Infinity===c?0:a.navigationStart-c;b=Math.max(0,Math.round(1E3*b.firstPaintTime+c)||0);break a}b=0}0<b&&g.le("fpt",b);re(a);qe.getEntriesByType&&Paa();a=g.v("SPEEDINDEX_FOR_ACTIONS",void 0);b=g.v("TIMING_ACTION",void 0);a&&-1<a.indexOf(b)&&(a=(0,g.yd)(),b=de(),c=(0,g.yd)(),0<b.Ek&&(ne("si",b.Ek),g.le("vsc",se(b.Zv)),g.le("sics",a),g.le("sice",c)));a=[];if(window.document.querySelector&&
qe&&qe.getEntriesByName)for(var d in te)if(b=window.document.querySelector(d)){var c="",e=b.nodeName;"SCRIPT"==e?c=b.src:"LINK"==e&&(c=b.href);c&&(b=qe.getEntriesByName(c))&&b[0]&&a.push(te[d]+"."+Math.round(b[0].duration))}a.length&&ne("rs",a.join(","))}};
ue=function(a){var b=fe(a);if(b.aft)return b.aft;a=g.v((a||"")+"TIMING_AFT_KEYS",["ol"]);for(var c=a.length,d=0;d<c;d++){var e=b[a[d]];if(e)return e}return window.NaN};
re=function(a){g.le("nreqs",a.requestStart,void 0);g.le("nress",a.responseStart,void 0);g.le("nrese",a.responseEnd,void 0);0<a.redirectEnd-a.redirectStart&&(g.le("nrs",a.redirectStart,void 0),g.le("nre",a.redirectEnd,void 0));0<a.domainLookupEnd-a.domainLookupStart&&(g.le("ndnss",a.domainLookupStart,void 0),g.le("ndnse",a.domainLookupEnd,void 0));0<a.connectEnd-a.connectStart&&(g.le("ntcps",a.connectStart,void 0),g.le("ntcpe",a.connectEnd,void 0));a.secureConnectionStart>=a.navigationStart&&0<a.connectEnd-
a.secureConnectionStart&&(g.le("nstcps",a.secureConnectionStart,void 0),g.le("ntcpe",a.connectEnd,void 0))};
se=function(a){return Math.round(qe.timing.navigationStart+a)};
Paa=function(){var a=window.location.protocol,b=qe.getEntriesByType("resource"),c=b.filter(function(b){return 0==b.name.indexOf(a+"//fonts.googleapis.com/css?family=")})[0],b=b.filter(function(b){return 0==b.name.indexOf(a+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});
c&&0<c.startTime&&0<c.responseEnd&&(g.le("wfcs",se(c.startTime)),g.le("wfce",se(c.responseEnd)));b&&0<b.startTime&&0<b.responseEnd&&(g.le("wffs",se(b.startTime)),g.le("wffe",se(b.responseEnd)))};
Be=function(a){var b=fe(a),c=ve(a).span,d=ee(a),e=!!d.ap,f=g.p("yt.timing.reportbuilder_");if(f){if(f=f(b,c,d,a))we(f,e),xe(a),ye(),ze(!1)}else{var k=g.v("CSI_SERVICE_NAME","youtube"),f={v:2,s:k,action:g.v((a||"")+"TIMING_ACTION",void 0)},l=d.srt;delete d.srt;void 0===b.srt&&(l||0===l||(l=qe.timing||{},l=Math.max(0,l.responseStart-l.navigationStart),(0,window.isNaN)(l)&&d.pt&&(l=d.pt)),l||0===l)&&(d.srt=Math.round(l));if(d.h5jse){var n=window.location.protocol+g.p("ytplayer.config.assets.js");(n=
qe.getEntriesByName?qe.getEntriesByName(n)[0]:null)?d.h5jse=Math.round(d.h5jse-n.responseEnd):delete d.h5jse}b.aft=ue(a);var n=b._start,u=fe(a),w=u.pbr,G=u.vc,u=u.pbs;w&&G&&u&&w<G&&G<u&&1==ee(a).yt_vis&&"youtube"==k&&(ne("yt_lt","hot_bg",a),k=b.vc,w=b.pbs,delete b.aft,d.aft=Math.round(w-k));for(var S in d)"_"!=S.charAt(0)&&(f[S]=d[S]);b.ps=(0,g.yd)();d={};S=[];for(var Y in b)"_"!=Y.charAt(0)&&(k=Math.round(b[Y]-n),g.Gc("enable_negative_ticks")||(k=Math.max(k,0)),d[Y]=k,S.push(Y+"."+k));f.rt=S.join(",");
b=f;Y=[];for(var ka in c)"_"!=ka.charAt(0)&&Y.push(ka+"."+Math.round(c[ka]));b.it=Y.join(",");(ka=g.p("ytdebug.logTiming"))&&ka(f,d,c);g.Gc("navigation_only_csi_reset")||(xe(a),ye(),ze(!1));g.v("EXP_DEFER_CSI_PING")?(Ae(),g.m("yt.timing.deferredPingArgs_",f,void 0),a=g.yb(Ae,0),g.m("yt.timing.deferredPingTimer_",a,void 0)):we(f,e);g.ae(Raa,new be(d.aft+(l||0)))}};
ke=function(a,b){if(!Ce(b)||!g.Gc("navigation_only_csi_reset")&&!b){var c=g.v((b||"")+"TIMING_ACTION",void 0),d=fe(b);if(g.p("yt.timing."+(b||"")+"ready_")&&c&&d._start&&ue(b)){(a||b)&&Be(b);var c=!0,e=g.v("TIMING_WAIT",[]);if(e.length)for(var f=0,k=e.length;f<k;++f)if(!(e[f]in d)){c=!1;break}c&&Be(b)}}};
we=function(a,b){if(g.v("DEBUG_CSI_DATA")){var c=g.p("yt.timing.csiData");c||(c=[],g.m("yt.timing.csiData",c,void 0));c.push({page:window.location.href,time:new Date,args:a})}g.v("EXP_DEFER_CSI_PING")&&(g.Ab(g.p("yt.timing.deferredPingTimer_")),g.m("yt.timing.deferredPingArgs_",null,void 0));var c="",d;for(d in a)c+="&"+d+"="+a[d];d="/csi_204?"+c.substring(1);window.navigator&&window.navigator.sendBeacon&&(!g.Gc("beacon_abandoned_only")||b)?g.Wd(d):g.Vd(d);ze(!0)};
Ae=function(a){if(g.v("EXP_DEFER_CSI_PING")){var b=g.p("yt.timing.deferredPingArgs_");b&&(a&&(b.yt_fss=a),we(b,!0))}};
De=function(a){g.m("yt.timing.ready_",a,void 0)};
me=function(a){var b=ve(a).nonce;if(!b){var c;a:{if(window.crypto&&window.crypto.getRandomValues)try{var d=Array(16),e=new window.Uint8Array(16);window.crypto.getRandomValues(e);for(b=0;b<d.length;b++)d[b]=e[b];c=d;break a}catch(f){}c=Array(16);for(d=0;16>d;d++){e=(0,g.F)();for(b=0;b<e%23;b++)c[d]=Math.random();c[d]=Math.floor(256*Math.random())}if(Ee)for(d=1,e=0;e<Ee.length;e++)c[d%16]=c[d%16]^c[(d-1)%16]/4^Ee.charCodeAt(e),d++}d=[];for(e=0;e<c.length;e++)d.push("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_".charAt(c[e]&
63));b=d.join("");ve(a).nonce=b}return b};
fe=function(a){return ve(a).tick};
ee=function(a){return ve(a).info};
ge=function(a){a=ve(a);"gel"in a||(a.gel={});return a.gel};
ve=function(a){return g.p("ytcsi."+(a||"")+"data_")||xe(a)};
xe=function(a){var b={tick:{},span:{},info:{}};g.m("ytcsi."+(a||"")+"data_",b,void 0);return b};
Ce=function(a){return!!g.p("yt.timing."+(a||"")+"pingSent_")};
ze=function(a){g.m("yt.timing.pingSent_",a,void 0)};
Fe=function(a){if(!Ce(void 0)){if(!g.Gc("send_empty_timing")){var b=g.v("CSI_SERVICE_NAME","youtube");if(!g.v("TIMING_ACTION",void 0)||!b)return}g.le("aa",void 0,void 0);ne("ap",1,void 0);ne("yt_fss",a,void 0);Be(void 0)}};
g.Ge=function(a,b){g.Vd("/gen_204?"+a,b)};
g.He=function(a){if(a.classList)return a.classList;a=a.className;return g.ja(a)&&a.match(/\S+/g)||[]};
g.H=function(a,b){return a.classList?a.classList.contains(b):g.Ja(g.He(a),b)};
g.I=function(a,b){a.classList?a.classList.add(b):g.H(a,b)||(a.className+=0<a.className.length?" "+b:b)};
g.J=function(a,b){a.classList?a.classList.remove(b):g.H(a,b)&&(a.className=(0,g.Ie)(g.He(a),function(a){return a!=b}).join(" "))};
g.Je=function(a,b,c){c?g.I(a,b):g.J(a,b)};
g.Le=function(a){var b=a.__yt_uid_key;b||(b=Ke(),a.__yt_uid_key=b);return b};
g.Me=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,g.y)(a.childNodes,function(a){b.appendChild(g.Me(a))}):b.innerHTML=a.innerHTML;
return b};
g.Ne=function(a){this.type="";this.state=this.source=this.data=this.currentTarget=this.relatedTarget=this.target=null;this.charCode=this.keyCode=0;this.shiftKey=this.ctrlKey=this.altKey=!1;this.rotation=this.clientY=this.clientX=0;this.scale=1;this.changedTouches=this.touches=null;if(a=a||window.event){this.event=a;for(var b in a)b in Saa||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=
b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;this.jn=a.pageX;this.mn=a.pageY}};
g.Pe=function(a,b,c,d){a.addEventListener&&("mouseenter"!=b||"onmouseenter"in window.document?"mouseleave"!=b||"onmouseenter"in window.document?"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"):b="mouseout":b="mouseover");return g.Ta(g.Oe,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
g.K=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=g.Pe(a,b,c,d);if(e)return e;var e=++Qe.count+"",f=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),k;k=f?function(d){d=new g.Ne(d);if(!g.Ud(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new g.Ne(b);
b.currentTarget=a;return c.call(a,b)};
k=xb(k);a.addEventListener?("mouseenter"==b&&f?b="mouseover":"mouseleave"==b&&f?b="mouseout":"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"),a.addEventListener(b,k,d)):a.attachEvent("on"+b,k);g.Oe[e]=[a,b,c,k,d];return e};
g.Re=function(a){a&&("string"==typeof a&&(a=[a]),(0,g.y)(a,function(a){if(a in g.Oe){var c=g.Oe[a],d=c[0],e=c[1],f=c[3],c=c[4];d.removeEventListener?d.removeEventListener(e,f,c):d.detachEvent&&d.detachEvent("on"+e,f);delete g.Oe[a]}}))};
g.Se=function(a){a=a||window.event;a.returnValue=!1;a.preventDefault&&a.preventDefault()};
g.Ue=function(){if(null==g.p("_lact",window)){var a=(0,window.parseInt)(g.v("LACT"),10),a=(0,window.isFinite)(a)?(0,g.F)()-Math.max(a,0):-1;g.m("_lact",a,window);-1==a&&Te();g.K(window.document,"keydown",Te);g.K(window.document,"keyup",Te);g.K(window.document,"mousedown",Te);g.K(window.document,"mouseup",Te);g.x("page-mouse",Te);g.x("page-scroll",Te);g.x("page-resize",Te)}};
Te=function(){null==g.p("_lact",window)&&(g.Ue(),g.p("_lact",window));var a=(0,g.F)();g.m("_lact",a,window);g.z("USER_ACTIVE")};
g.Ve=function(){var a=g.p("_lact",window);return null==a?-1:Math.max((0,g.F)()-a,0)};
We=function(a){a=a||{};this.url=a.url||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||g.Xa(Taa);this.assets=a.assets||{};this.attrs=a.attrs||g.Xa(Uaa);this.params=a.params||g.Xa(Vaa);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};
g.Xe=function(a){a instanceof We||(a=new We(a));return a};
Ze=function(){return null!=g.Ye};
g.$e=function(){return g.Ye?g.Ye.invoke():null};
af=function(){return(0,window.parseInt)(g.v("DCLKSTAT",0),10)};
g.bf=function(a){this.A=a||{cookie:""}};
g.df=function(a){a=(a.A.cookie||"").split(g.cf);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
g.ff=function(a,b,c,d){g.ef.set(""+a,b,c,"/",d||"youtube.com")};
g.jf=function(a,b,c){var d=g.v("VALID_SESSION_TEMPDATA_DOMAINS",[]),e=g.Uc(window.location.href);e&&d.push(e);e=g.Uc(a);if(g.Ja(d,e)||!e&&g.sa(a,"/"))if(a=g.Vc(a),a=g.Wc(a))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&(gf(a,b,c),hf(b))):(gf(a,b),hf(b))};
gf=function(a,b,c){a="ST-"+g.Ca(a).toString(36);c=c||5;b=b?g.$c(b):"";g.ff(a,b,c)};
hf=function(a){if(a){a=a.itct||a.ved;var b=g.p("yt.logging.screenreporter.storeParentElement");a&&b&&b(new g.qd(a))}};
g.kf=function(a,b,c){c=c||"";g.zc(window.location,g.ad(a,b||{})+c)};
g.lf=function(a,b){b&&g.jf(a,b);(window.ytspf||{}).enabled?window.spf.navigate(a):g.kf(a)};
g.mf=function(a,b,c){var d=g.v("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&g.jf(a,b);if(c)return!1;g.lf(a);return!0};
g.pf=function(){return g.Md?"Webkit":g.nf?"Moz":g.E?"ms":g.of?"O":null};
g.qf=function(){return g.Md?"-webkit":g.nf?"-moz":g.E?"-ms":g.of?"-o":null};
g.rf=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
g.sf=function(a,b){return a&&b?b instanceof g.rf?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};
g.tf=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};
g.vf=function(a,b){var c=uf[b];if(!c){var d=Da(b),c=d;void 0===a.style[d]&&(d=g.pf()+g.Fa(d),void 0!==a.style[d]&&(c=d));uf[b]=c}return c};
g.wf=function(a,b){var c=a.style[Da(b)];return"undefined"!==typeof c?c:a.style[g.vf(a,b)]||""};
g.xf=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};
g.yf=function(a,b){a.style.height=g.xf(b,!0)};
g.zf=function(a,b){a.style.width=g.xf(b,!0)};
g.Af=function(a,b){a.style.display=b?"":"none"};
g.Cf=function(){var a=g.ef.get("PREF",void 0);if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(g.Bf[d]=c.toString())}};
Df=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};
Ef=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};
g.Ff=function(a){a=void 0!==g.Bf[a]?g.Bf[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};
g.Gf=function(a,b){return!!((g.Ff("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
g.Hf=function(a,b){(a=g.C(a))&&a.style&&(g.Af(a,b),g.Je(a,"hid",!b))};
g.If=function(a){return(a=g.C(a))?!("none"==a.style.display||g.H(a,"hid")):!1};
Waa=function(a){if(a=g.C(a))g.If(a)?(g.Af(a,!1),g.I(a,"hid")):(g.Af(a,!0),g.J(a,"hid"))};
g.L=function(a){(0,g.y)(arguments,function(a){!g.ia(a)||a instanceof window.Element?g.Hf(a,!0):(0,g.y)(a,function(a){g.L(a)})})};
g.M=function(a){(0,g.y)(arguments,function(a){!g.ia(a)||a instanceof window.Element?g.Hf(a,!1):(0,g.y)(a,function(a){g.M(a)})})};
g.Jf=function(a){(0,g.y)(arguments,function(a){g.ia(a)?(0,g.y)(a,function(a){g.Jf(a)}):Waa(a)})};
g.Lf=function(){this.A=this.minor=this.major=0;this.C="";var a=g.p("window.navigator.plugins"),b=g.p("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,f=c.length;e<f;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.C=b;b=a;this.major=b[0];this.minor=b[1];this.A=b[2];if(0>=this.major){var k,l,n,u;if(g.Kf)try{k=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(w){k=null}else n=window.document.body,u=window.document.createElement("object"),u.setAttribute("type","application/x-shockwave-flash"),k=n.appendChild(u);if(k&&"GetVariable"in k)try{l=k.GetVariable("$version")}catch(w){l=""}n&&u&&n.removeChild(u);(k=l||
"")?(k=k.split(" ")[1].split(","),k=[(0,window.parseInt)(k[0],10)||0,(0,window.parseInt)(k[1],10)||0,(0,window.parseInt)(k[2],10)||0]):k=[0,0,0];this.major=k[0];this.minor=k[1];this.A=k[2]}};
Mf=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.major>b[0]||a.major==b[0]&&a.minor>b[1]||a.major==b[0]&&a.minor==b[1]&&a.A>=b[2]};
Nf=function(a){return-1<a.C.indexOf("Gnash")&&-1==a.C.indexOf("AVM2")||9==a.major&&1==a.minor||9==a.major&&0==a.minor&&1==a.A?!1:9<=a.major};
Xaa=function(a){return g.Of?!Mf(a,11,2):g.Pf?!Mf(a,11,3):!Nf(a)};
Qf=function(a,b,c){if(b){a=g.ja(a)?g.Dd(a):a;var d=g.Xa(c.attrs);d.tabindex=0;var e=g.Xa(c.params);e.flashvars=g.$c(c.args);if(g.Kf){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var f in d)b.setAttribute(f,d[f]);for(f in e)d=window.document.createElement("param"),d.setAttribute("name",f),d.setAttribute("value",e[f]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");b.setAttribute("name",
d.id);for(f in d)b.setAttribute(f,d[f]);for(f in e)b.setAttribute(f,e[f])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};
g.Tf=function(a,b){a=g.ja(a)?g.Dd(a):a;b=g.Xe(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=g.Lf.getInstance();Mf(c,b.minVersion)?(c=Rf(b,c),Qf(a,c,b)):Sf(a,b,c)};
Uf=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=g.Xe(a);var d=!!b,e=g.C(a.attrs.id),f=e?e.parentNode:null;if(e&&f){if(window!=window.top){var k=null;if(window.document.referrer){var l=window.document.referrer.substring(0,128);waa(l)||(k=l)}else k="unknown";k&&(d=!0,a.args.framer=k)}k=g.Lf.getInstance();if(Mf(k,a.minVersion)){var l=Rf(a,k),n="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(n=e.getAttribute("src")||e.movie);(n!=l||d)&&Qf(f,l,a);Xaa(k)&&Yaa()}else Sf(f,a,k);c&&c()}else g.yb(function(){Uf(a,
b,c)},50)}};
Sf=function(a,b,c){0==c.major&&b.fallback?b.fallback():0==c.major&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+g.Fb("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};
Rf=function(a,b){var c;(c=Nf(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!Mf(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.url};
Yaa=function(){var a=g.C("flash10-promo-div"),b=g.Gf(g.Cf.getInstance(),107);a&&!b&&g.L(a)};
g.Vf=function(a,b){var c=a.match(Zaa);window.spf.style.load(a,c?c[1]:"",b)};
g.Wf=function(a){g.pb.call(this);this.A=[];this.C=a||this};
Xf=function(a,b,c,d){d=xb((0,g.q)(d,a.C));b.addEventListener(c,d);a.A.push({target:b,name:c,Ob:d})};
Yf=function(a){for(;a.A.length;){var b=a.A.pop();b.target.removeEventListener(b.name,b.Ob)}};
ag=function(a,b){g.pb.call(this);this.P=this.D=a;this.ga=b;this.K=!1;this.api={};this.Qa=this.T=null;this.Y=new g.tb;g.sb(this,this.Y);this.B={};this.F=this.Wa=this.C=this.kb=this.A=null;this.aa=!1;this.W=this.G=this.M=this.R=null;this.Ya={};this.Tb=["onReady"];this.ea=new g.Wf(this);g.sb(this,this.ea);this.rb=null;this.Db=window.NaN;this.ha={};Zf(this);this.ge("onDetailedError",(0,g.q)(this.TI,this));this.ge("onTabOrderChange",(0,g.q)(this.ny,this));this.ge("onTabAnnounce",(0,g.q)(this.cp,this));
this.ge("WATCH_LATER_VIDEO_ADDED",(0,g.q)(this.WI,this));this.ge("WATCH_LATER_VIDEO_REMOVED",(0,g.q)(this.XI,this));g.$f||(this.ge("onMouseWheelCapture",(0,g.q)(this.AI,this)),this.ge("onMouseWheelRelease",(0,g.q)(this.BI,this)));this.ge("onAdAnnounce",(0,g.q)(this.cp,this));this.H=new g.Wf(this);g.sb(this,this.H);this.gb=!1;this.bb=null};
cg=function(a,b){a.kb=b;a.A=b.clone();a.C=a.A.attrs.id||a.C;"video-player"==a.C&&(a.C=a.ga,a.A.attrs.id=a.ga);a.P.id==a.C&&(a.C+="-player",a.A.attrs.id=a.C);a.A.args.enablejsapi="1";a.A.args.playerapiid=a.ga;a.Wa||(a.Wa=bg(a,a.A.args.jsapicallback||"onYouTubePlayerReady"));a.A.args.jsapicallback=null;var c=a.A.attrs.width;c&&g.zf(a.P,Number(c)||c);(c=a.A.attrs.height)&&g.yf(a.P,Number(c)||c)};
dg=function(a){a.A.loaded||(a.A.loaded=!0,"0"!=a.A.args.autoplay?a.api.loadVideoByPlayerVars(a.A.args):a.api.cueVideoByPlayerVars(a.A.args))};
eg=function(a){if(!g.ca(a.A.disable.flash)){var b=a.A.disable,c;c=Mf(g.Lf.getInstance(),a.A.minVersion);b.flash=!c}return!a.A.disable.flash};
hg=function(a,b){if((!b||(5!=($aa[b.errorCode]||5)?0:-1!=aba.indexOf(b.errorCode)))&&eg(a)){var c=fg(a);c&&c.stopVideo&&c.stopVideo();var d=a.A;c&&c.getUpdatedConfigurationData&&(c=c.getUpdatedConfigurationData(),d=g.Xe(c));d.args.autoplay=1;d.args.html5_unavailable="1";cg(a,d);gg(a,"flash")}};
gg=function(a,b){if(!a.isDisposed()){if(!b){var c;if(!(c=!a.A.html5&&eg(a))){if(!g.ca(a.A.disable.html5)){var d;c=!0;void 0!=a.A.args.deviceHasDisplay&&(c=a.A.args.deviceHasDisplay);if(2.2==ig)d=!0;else{a:{var e=c;c=g.p("yt.player.utils.videoElement_");c||(c=window.document.createElement("video"),g.m("yt.player.utils.videoElement_",c,void 0));try{if(c.canPlayType)for(var e=e?bba:cba,f=0;f<e.length;f++)if(c.canPlayType(e[f])){d=null;break a}d="fmt.noneavailable"}catch(k){d="html5.missingapi"}}d=!d}d&&
(d=jg(a)||a.A.assets.js);a.A.disable.html5=!d;d||(a.A.args.html5_unavailable="1")}c=!!a.A.disable.html5}b=c?eg(a)?"flash":"unsupported":"html5"}("flash"==b?a.VO:"html5"==b?a.WO:a.XO).call(a)}};
jg=function(a){var b=!0,c=fg(a);c&&a.A&&(a=a.A,b=g.A(c,"version")==a.assets.js);return b&&!!g.p("yt.player.Application.create")};
fg=function(a){var b=g.C(a.C);!b&&a.P&&a.P.querySelector&&(b=a.P.querySelector("#"+a.C));return b};
kg=function(a,b,c){var d=b[c];return function(){try{return a.rb=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&"sendAbandonmentPing"!=c&&(e.message+=" ("+c+")",a.rb=e,g.Cb(e,"WARNING"))}}};
Zf=function(a){a.K=!1;if(a.Qa)for(var b in a.B)a.Qa(b,a.B[b]);for(var c in a.ha)g.Ab((0,window.parseInt)(c,10));a.ha={};a.T=null;a.Qa=null;for(var d in a.api)a.api[d]=null;a.api.addEventListener=(0,g.q)(a.ge,a);a.api.removeEventListener=(0,g.q)(a.ZM,a);a.api.destroy=(0,g.q)(a.dispose,a);a.api.getLastError=(0,g.q)(a.Oz,a);a.api.getPlayerType=(0,g.q)(a.dA,a);a.api.getCurrentVideoConfig=(0,g.q)(a.lz,a);a.api.loadNewVideoConfig=(0,g.q)(a.Bo,a);a.api.isReady=(0,g.q)(a.kP,a)};
bg=function(a,b){var c=b;if("string"==typeof b){if(a.Ya[b])return a.Ya[b];c=function(){var a=g.p(b);a&&a.apply(g.da,arguments)};
a.Ya[b]=c}return c?c:null};
dba=function(a,b){var c="ytPlayer"+b+a.ga;a.B[b]=c;g.da[c]=function(c){var e=g.yb(function(){a.isDisposed()||(a.Y.oa(b,c),g.Va(a.ha,String(e)))},0);
g.Wa(a.ha,String(e),!0)};
return c};
lg=function(a){return(a=fg(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
mg=function(a){g.le("dcp");a.cancel();Zf(a);a.F=null;a.A&&(a.A.loaded=!1);var b=fg(a);"html5"==lg(a)?a.M=b:b&&b.destroy&&b.destroy();g.Qd(a.D);Yf(a.ea);a.G=null;a.W=null};
g.pg=function(a,b){a=g.ja(a)?g.Dd(a):a;b=g.Xe(b);var c=g.ng+"_"+g.pa(a),d=g.og[c];if(d)return d.Bo(b),d.api;d=new ag(a,c);g.og[c]=d;g.z("player-added",d.api);g.qb(d,g.r(eba,d));g.yb(function(){d.Bo(b)},0);
return d.api};
eba=function(a){g.og[a.getId()]=null};
g.qg=function(a){a=g.C(a);if(!a)return null;var b=g.ng+"_"+g.pa(a),c=g.og[b];c||(c=new ag(a,b),g.og[b]=c);return c.api};
g.rg=function(){return g.H(g.C("page-container"),"remote-connected")};
fba=function(){g.m("yt.abuse.botguardInitialized",Ze,void 0);g.m("yt.abuse.invokeBotguard",g.$e,void 0);g.m("yt.abuse.dclkstatus.checkDclkStatus",af,void 0);g.m("yt.player.exports.navigate",g.mf,void 0);g.m("yt.player.embed",g.pg,void 0);g.m("yt.player.getPlayerByElement",g.qg,void 0);g.m("yt.util.activity.init",g.Ue,void 0);g.m("yt.util.activity.getTimeSinceActive",g.Ve,void 0);g.m("yt.util.activity.setTimestamp",Te,void 0);var a=g.p("ytplayer.config");sg(a);g.p("ytspf.enabled")&&(tg=g.zb(ug,5E3),
(a=g.vg())?(a.addEventListener("onReady",ug),a.addEventListener("onStateChange",ug)):wg("unable to init PP monitor"))};
sg=function(a){for(var b in g.og){var c=g.og[b];c&&c.cancel()}if(a=a||null){b=g.vg();var d=!0,c=g.xg;g.xg=null;b&&b.getVideoData&&c&&(d=b.getVideoData(),d=!!c.fullscreen||d.video_id!=a.args.video_id||d.list!=a.args.list||d.video_id!=c.videoId||d.list!=c.listId);d?(yg="",g.pg("player-api",a)):b.playVideo();a=g.Xe(a);a.loaded=!0}ug();g.m("ytplayer.config",a,void 0)};
g.vg=function(){var a=g.p("yt.player.getPlayerByElement");return a?a("player-api"):null};
ug=function(){var a=g.vg();if(a){var b;b=g.C("player");b=!b||g.H(b,"off-screen");var c=1==(a&&a.isReady()?a.getPlayerState():void 0),d="watch"==g.v("PAGE_NAME"),e=g.rg();!c||d||e||(wg("PP playing off watch (paused)"),a.pauseVideo());b&&d?wg("PP off-screen on watch"):b||d||wg("PP !off-screen off watch")}};
wg=function(a){var b=g.v("PAGE_NAME");b&&(b=[b,yg,g.p("_spf_state.nav-counter")],a+="("+b.join(",")+")",g.m("yt.www.persistentplayer.issue",a,void 0),g.Cb(Error(a),"WARNING"))};
g.zg=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};
g.Ag=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};
g.Cg=function(a,b){this.A=0;this.K=void 0;this.D=this.C=this.B=null;this.F=this.G=!1;if(a!=g.ea)try{var c=this;a.call(b,function(a){g.Bg(c,2,a)},function(a){g.Bg(c,3,a)})}catch(d){g.Bg(this,3,d)}};
Dg=function(){this.next=this.context=this.C=this.D=this.A=null;this.B=!1};
g.Fg=function(a,b,c){var d=Eg.get();d.D=a;d.C=b;d.context=c;return d};
gba=function(a,b,c){Gg(a,b,c,null)||mb(g.r(b,a))};
g.Hg=function(a){return new g.Cg(function(b,c){var d=a.length,e=[];if(d)for(var f=function(a,c){d--;e[a]=c;0==d&&b(e)},k=function(a){c(a)},l=0,n;l<a.length;l++)n=a[l],gba(n,g.r(f,l),k);
else b(e)})};
Ig=function(a,b){if(0==a.A)if(a.B){var c=a.B;if(c.C){for(var d=0,e=null,f=null,k=c.C;k&&(k.B||(d++,k.A==a&&(e=k),!(e&&1<d)));k=k.next)e||(f=k);e&&(0==c.A&&1==d?Ig(c,b):(f?(d=f,d.next==c.D&&(c.D=d),d.next=d.next.next):Jg(c),Kg(c,e,3,b)))}a.B=null}else g.Bg(a,3,b)};
g.Mg=function(a,b){a.C||2!=a.A&&3!=a.A||Lg(a);a.D?a.D.next=b:a.C=b;a.D=b};
g.Og=function(a,b,c,d){var e=g.Fg(null,null,null);e.A=new g.Cg(function(a,k){e.D=b?function(c){try{var e=b.call(d,c);a(e)}catch(u){k(u)}}:a;
e.C=c?function(b){try{var e=c.call(d,b);!g.ca(e)&&b instanceof Ng?k(b):a(e)}catch(u){k(u)}}:k});
e.A.B=a;g.Mg(a,e);return e.A};
g.Bg=function(a,b,c){0==a.A&&(a==c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.A=1,Gg(c,a.W,a.H,a)||(a.K=c,a.A=b,a.B=null,Lg(a),3!=b||c instanceof Ng||hba(a,c)))};
Gg=function(a,b,c,d){if(a instanceof g.Cg)return g.Mg(a,g.Fg(b||g.ea,c||null,d)),!0;if(g.Ag(a))return a.then(b,c,d),!0;if(g.na(a))try{var e=a.then;if(g.ma(e))return iba(a,e,b,c,d),!0}catch(f){return c.call(d,f),!0}return!1};
iba=function(a,b,c,d,e){function f(a){l||(l=!0,d.call(e,a))}
function k(a){l||(l=!0,c.call(e,a))}
var l=!1;try{b.call(a,k,f)}catch(n){f(n)}};
Lg=function(a){a.G||(a.G=!0,mb(a.P,a))};
Jg=function(a){var b=null;a.C&&(b=a.C,a.C=b.next,b.next=null);a.C||(a.D=null);return b};
Kg=function(a,b,c,d){if(3==c&&b.C&&!b.B)for(;a&&a.F;a=a.B)a.F=!1;if(b.A)b.A.B=null,Pg(b,c,d);else try{b.B?b.D.call(b.context):Pg(b,c,d)}catch(e){Qg.call(null,e)}fb(Eg,b)};
Pg=function(a,b,c){2==b?a.D.call(a.context,c):a.C&&a.C.call(a.context,c)};
hba=function(a,b){a.F=!0;mb(function(){a.F&&Qg.call(null,b)})};
Ng=function(a){g.ra.call(this,a)};
lba=function(){var a=g.Id(),b=new g.tf(0,0,a.width,a.height);ne("vps",a.width+"."+a.height);g.le("vpc");for(var a=window.document.querySelectorAll(".yt-lockup-thumbnail img[data-ytimg]"),c=a.length,d=[],e=!0,f=0;f<c;f++){var k=a[f],l;a:{l=b;for(var n=k,u=window.document.body;n!=u;){var w=g.Le(n);if(w in Rg)break;var G=window.getComputedStyle(n);if("none"==G.display||"hidden"==G.visibility){l=!1;break a}G=n.getBoundingClientRect();G=new g.tf(G.left,G.top,G.width,G.height);if(!(l.left<=G.left+G.width&&
G.left<=l.left+l.width&&l.top<=G.top+G.height&&G.top<=l.top+l.height)){l=!1;break a}Rg[w]=!0;n=n.parentElement}l=!0}l&&(d.push(jba(k)),k.loadTime||(e=!1))}e&&ne("yt_eil",1);ne("vpni",d.length);g.le("vpcc");return g.Hg(d).then(kba)};
kba=function(a){return Math.max(Math.max.apply(null,a),0)};
jba=function(a){return new g.Cg(function(b){if(a.loadTime)ne("vpil",++Sg),b((0,window.parseInt)(a.loadTime,10));else{var c=g.K(a,"load",function(){if(a.loadTime){var d=(0,window.parseInt)(a.loadTime,10);g.Re(c);ne("vpil",++Sg);b(d)}});
Tg.push(c)}})};
Wg=function(){g.le("ol");g.v("CSI_TICK_PAINT_TIME")?window.requestAnimationFrame&&!window.document.hidden?window.requestAnimationFrame(function(){(0,window.setTimeout)(function(){g.le("cpt");Ug()},0)}):window.document.hidden?(g.le("cpt"),Ug()):(0,window.setTimeout)(function(){g.le("cpt");
Ug()},0):Ug();
g.v("CSI_VIEWPORT")&&(Vg=lba(),Vg.then(function(a){g.le("vpl",a);Vg=null},function(){}))};
Ug=function(){Xg("init");var a=g.v("PAGE_NAME",void 0);a&&Xg("init-"+a)};
Xg=function(a){g.Nb()?Yg.push(g.Ob(g.r(g.Mb,a),0)):g.z(a)};
Zg=function(){g.Sb(Yg);Sg=Yg.length=0;Rg={};g.Re(Tg);Tg.length=0;Vg&&(Vg.cancel(),Vg=null);var a=g.v("PAGE_NAME",void 0);a&&g.Mb("dispose-"+a);g.Mb("dispose")};
mba=function(){Wg()};
nba=function(){g.v("TIMING_REPORT_ON_UNLOAD")&&ke(!0);Fe("u");Ae("u");Zg();g.Mb("pageunload")};
$g=function(){Te()};
ah=function(){window.yt_spf_loaded_history=!0;g.v("EXP_LACT_HISTORY")&&Te()};
fh=function(){bh=1;ch=dh=0;g.v("TIMING_REPORT_ON_UNLOAD")&&ke(!0);Fe("n");Ae("n");xe(void 0);ye();ze(!1);oe("n");je("mark_navigation_requested");eh(oba);g.Mb("navigate")};
jh=function(a){a=a.detail.part||a.detail.partial;g.le("nc"+dh);++dh;if(!a.data||!a.data.deferDispose){var b=1==bh;bh=2;b?(eh(pba),gh()):eh(qba);if(b=a.data&&a.data.swfcfg)hh(a.timing,b.args),ih(b)}};
kh=function(){g.le("np"+ch);++ch};
lh=function(a){a=a.detail.response;var b=1==bh;bh=3;b&&(eh(rba),gh());if(b=a.data&&a.data.swfcfg)hh(a.timing,b.args),ih(b)};
oh=function(a){g.le("nd");a=a.detail.response;g.mh=a.cacheKey;a=a.timing;var b=window._spf_state;ne("yt_nav",b&&b["nav-counter"]||0);oe("ne",a.responseStart);ne("srt",Math.max(0,a.responseStart-a.navigationStart));ne("yt_lt",a.spfCached?"hot":"warm");ne("yt_pft",+!!a.spfPrefetched);g.le("pfs",a.fetchStart);g.le("pfrs",a.responseStart);"redirectStart"in a&&re(a);eh(nh);window.document.getElementById("content").style.height="";Wg();bh=0};
ph=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),g.Cb(a)};
qh=function(a){g.Ge(g.$c({spfreload:"1",url:a.detail.url,reason:a.detail.reason}))};
tba=function(){sba();g.wb("SERVED_VIA_SPF_HISTORY",!!window.yt_spf_loaded_history);window.yt_spf_loaded_history=!1};
uba=function(){};
gh=function(){var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");Zg();var a=g.v("TIMING_ACTION"),b;for(b in g.vb)delete g.vb[b];g.wb("PREVIOUS_ACTION",a);g.m("ytplayer.config",null,void 0);if((b=g.vg())&&b.stopVideo){if(b.stopVideo(),b=b.getLastError())yg=b,(b=g.C("movie_player"))&&b.stopVideo?(b.stopVideo(),yg="recovered"):yg="missing2"}else yg="missing";ug()};
ih=function(a){"cfg"in fe(void 0)||g.le("cfg");sg(a)};
eh=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.appendChild(window.document.createElement("dt")),b.appendChild(window.document.createElement("dd")),window.document.body.appendChild(b));g.Qb(rh);rh=g.Pb(function(){var c=a[0],d=a[1],e=a[2];b.className="";var f=b.style;f.transitionDuration=f.webkitTransitionDuration=c+"ms";f.width=d+"%";g.Ab(sh);sh=g.yb(function(){b.className=e},c)},0)};
sba=function(){var a=nh[0]+50;g.Ab(sh);sh=g.yb(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};
hh=function(a,b){var c=a&&a.spfCached,d=a&&a.spfPrefetched,e=[];c&&!d&&(0,g.y)(vba,function(a){a in b&&(delete b[a],e.push(a))});
g.v("EXP_DEBUG_PREFETCH")&&(e.sort(),c={a:"removeNonCacheableVideoVars",cached:c,prefetched:d,deleted:e.join("")},g.Ge(g.$c(c)))};
wba=function(){var a="/sw.js",b=g.v("SERVICE_WORKER_VFL",void 0);b&&(a+="?vfl="+b);window.navigator.serviceWorker.register(a,{scope:"/"})};
yba=function(a){a&&window.navigator.serviceWorker.register("/sw.js?0",{scope:"/"}).then(th,xba)};
xba=function(){window.navigator.serviceWorker.getRegistration().then(th)};
th=function(a){a&&a.unregister()};
uh=function(){g.Tb.call(this,"www/base");this.B=0};
vh=function(a){(a=a.detail.name)&&Xb(a)};
g.aa=[];g.wh=g.wh||{};g.da=this;oa="closure_uid_"+(1E9*Math.random()>>>0);aaa=0;g.F=Date.now||function(){return+new Date};g.qa[" "]=g.ea;g.t(g.ra,Error);g.ra.prototype.name="CustomError";var eaa,faa,gaa,haa,iaa,jaa,daa;g.za=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
eaa=/&/g;faa=/</g;gaa=/>/g;haa=/"/g;iaa=/'/g;jaa=/\x00/g;daa=/[\x00&<>"']/;g.xh=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
g.zba=2147483648*Math.random()|0;g.Ia=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;
if(g.ja(a))return g.ja(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
g.Aba=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;
0>c&&(c=Math.max(0,a.length+c));if(g.ja(a))return g.ja(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};
g.y=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ja(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
g.Ie=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,k=g.ja(a)?a.split(""):a,l=0;l<d;l++)if(l in k){var n=k[l];
b.call(c,n,l,a)&&(e[f++]=n)}return e};
g.yh=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=g.ja(a)?a.split(""):a,k=0;k<d;k++)k in f&&(e[k]=b.call(c,f[k],k,a));
return e};
g.zh=Array.prototype.reduce?function(a,b,c,d){d&&(b=(0,g.q)(b,d));return Array.prototype.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;
(0,g.y)(a,function(c,k){e=b.call(d,e,c,k,a)});
return e};
g.Ah=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ja(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;
return!1};
g.Bh=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ja(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;
return!0};g.Ch=g.Pa(!1);g.Dh=g.Pa(!0);g.Eh=g.Pa(null);var Ya="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");a:{var Fh=g.da.navigator;if(Fh){var Gh=Fh.userAgent;if(Gh){g.$a=Gh;break a}}g.$a=""};var ob;eb.prototype.get=function(){var a;0<this.C?(this.C--,a=this.A,this.A=a.next,a.next=null):a=this.B();return a};var lb=new eb(function(){return new hb},function(a){a.reset()},100);
gb.prototype.remove=function(){var a=null;this.A&&(a=this.A,this.A=this.A.next,this.A||(this.C=null),a.next=null);return a};
hb.prototype.set=function(a,b){this.oe=a;this.scope=b;this.next=null};
hb.prototype.reset=function(){this.next=this.scope=this.oe=null};var ib,jb=!1,kb=new gb;g.pb.prototype.Md=!1;g.pb.prototype.isDisposed=function(){return this.Md};
g.pb.prototype.dispose=function(){this.Md||(this.Md=!0,this.U())};
g.pb.prototype.U=function(){if(this.Jb)for(;this.Jb.length;)this.Jb.shift()()};g.t(g.tb,g.pb);g.h=g.tb.prototype;g.h.subscribe=function(a,b,c){var d=this.sd[a];d||(d=this.sd[a]=[]);var e=this.D;this.A[e]=a;this.A[e+1]=b;this.A[e+2]=c;this.D=e+3;d.push(e);return e};
g.h.unsubscribe=function(a,b,c){if(a=this.sd[a]){var d=this.A;if(a=g.Ha(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.td(a)}return!1};
g.h.td=function(a){var b=this.A[a];if(b){var c=this.sd[b];0!=this.B?(this.C.push(a),this.A[a+1]=g.ea):(c&&g.La(c,a),delete this.A[a],delete this.A[a+1],delete this.A[a+2])}return!!b};
g.h.oa=function(a,b){var c=this.sd[a];if(c){for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];if(this.F)for(e=0;e<c.length;e++){var k=c[e];maa(this.A[k+1],this.A[k+2],d)}else{this.B++;try{for(e=0,f=c.length;e<f;e++)k=c[e],this.A[k+1].apply(this.A[k+2],d)}finally{if(this.B--,0<this.C.length&&0==this.B)for(;c=this.C.pop();)this.td(c)}}return 0!=e}return!1};
g.h.clear=function(a){if(a){var b=this.sd[a];b&&((0,g.y)(b,this.td,this),delete this.sd[a])}else this.A.length=0,this.sd={}};
g.h.ob=g.ba(1);g.h.U=function(){g.tb.L.U.call(this);this.clear();this.C.length=0};g.vb=window.yt&&window.yt.config_||window.ytcfg&&window.ytcfg.data_||{};g.m("yt.config_",g.vb,void 0);g.m("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);g.Db=window.yt&&window.yt.msgs_||g.p("window.ytcfg.msgs")||{};g.m("yt.msgs_",g.Db,void 0);g.yd=window.performance&&window.performance.timing&&window.performance.now?function(){return window.performance.timing.navigationStart+window.performance.now()}:function(){return(new Date).getTime()};
g.Kf="Microsoft Internet Explorer"==window.navigator.appName;var Bba=g.p("yt.pubsub.instance_")||new g.tb;g.tb.prototype.subscribe=g.tb.prototype.subscribe;g.tb.prototype.unsubscribeByKey=g.tb.prototype.td;g.tb.prototype.publish=g.tb.prototype.oa;g.tb.prototype.clear=g.tb.prototype.clear;g.m("yt.pubsub.instance_",Bba,void 0);var Ib=g.p("yt.pubsub.subscribedKeys_")||{};g.m("yt.pubsub.subscribedKeys_",Ib,void 0);var Kb=g.p("yt.pubsub.topicToKeys_")||{};g.m("yt.pubsub.topicToKeys_",Kb,void 0);var Jb=g.p("yt.pubsub.isSynchronous_")||{};
g.m("yt.pubsub.isSynchronous_",Jb,void 0);var Hb=g.p("yt.pubsub.skipSubId_")||null;g.m("yt.pubsub.skipSubId_",Hb,void 0);g.h=g.Tb.prototype;g.h.lN=function(){this.Oj()||this.init()};
g.h.enable=function(){this.A=1;(0,g.y)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.lN,this),this.subscribe("dispose-"+a,this.dispose,this),g.v("PAGE_NAME")==a&&g.Ub(this))},this)};
g.h.init=function(){g.Qb(this.C);this.A=2;this.G&&this.G()};
g.h.Oj=function(){return 2==this.A};
g.h.dispose=function(){this.A=3;g.Qb(this.C);this.F&&this.F()};
g.h.disable=function(){this.A=4;this.clear();try{this.dispose()}catch(a){g.Cb(a)}};
g.h.subscribe=function(a,b,c){a=g.x(a,b,c);this.D.push(a);return a};
g.h.clear=function(){g.Lb(this.D);this.D=[]};var Vb=g.p("yt.modules.registry_")||{};g.m("yt.modules.registry_",Vb,void 0);var taa={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};g.Cba=RegExp("[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.Dba=RegExp("^[^\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.Hh=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");$b.prototype.Pf=!0;$b.prototype.Oe=function(){return this.A};
$b.prototype.toString=function(){return"Const{"+this.A+"}"};
var Zb={};dc.prototype.Pf=!0;var cc={};dc.prototype.Oe=function(){return this.A};
var paa=fc(""),oaa=/^([-,."'%_!# a-zA-Z0-9]+|(?:rgb|hsl)a?\([0-9.%, ]+\))$/;g.ic.prototype.Pf=!0;g.ic.prototype.Oe=function(){return this.A};
g.ic.prototype.um=!0;g.ic.prototype.zg=function(){return 1};
var qaa=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i,hc={};g.kc("about:blank");g.nc.prototype.Pf=!0;g.nc.prototype.Oe=function(){return this.A};
g.nc.prototype.um=!0;g.nc.prototype.zg=function(){return 1};
var mc={};var uc,saa,raa,pc;g.qc.prototype.um=!0;g.qc.prototype.zg=function(){return this.C};
g.qc.prototype.Pf=!0;g.qc.prototype.Oe=function(){return this.A};
uc=/^[a-zA-Z0-9-]+$/;saa={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0};raa={APPLET:!0,BASE:!0,EMBED:!0,IFRAME:!0,LINK:!0,MATH:!0,META:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0};pc={};g.Eba=g.sc("<!DOCTYPE html>",0);g.Ih=g.sc("",0);g.Jh=g.sc("<br>",0);var Cc={};var uaa=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,vaa=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;g.Fba=Math.sign||function(a){return 0<a?1:0>a?-1:a};g.Kh="StopIteration"in g.da?g.da.StopIteration:{message:"StopIteration",stack:""};var Nh,Oh,Kc,Sh;g.of=g.ab("Opera");g.E=g.bb();g.Lh=g.ab("Edge");g.Mh=g.Lh||g.E;g.nf=g.ab("Gecko")&&!(g.xa(g.$a.toLowerCase(),"webkit")&&!g.ab("Edge"))&&!(g.ab("Trident")||g.ab("MSIE"))&&!g.ab("Edge");g.Md=g.xa(g.$a.toLowerCase(),"webkit")&&!g.ab("Edge");g.Md&&g.ab("Mobile");g.Pf=g.ab("Macintosh");g.Of=g.ab("Windows");g.Gba=g.ab("Linux")||g.ab("CrOS");Nh=g.da.navigator||null;Nh&&g.xa(Nh.appVersion||"","X11");g.Hba=g.ab("Android");g.Iba=g.Ic();g.Jba=g.ab("iPad");g.Kba=g.ab("iPod");
a:{var Ph="",Qh=function(){var a=g.$a;if(g.nf)return/rv\:([^\);]+)(\)|;)/.exec(a);if(g.Lh)return/Edge\/([\d\.]+)/.exec(a);if(g.E)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(g.Md)return/WebKit\/(\S+)/.exec(a);if(g.of)return/(?:Version)[ \/]?(\S+)/.exec(a)}();
Qh&&(Ph=Qh?Qh[1]:"");if(g.E){var Rh=Jc();if(null!=Rh&&Rh>(0,window.parseFloat)(Ph)){Oh=String(Rh);break a}}Oh=Ph}g.Lc=Oh;Kc={};Sh=g.da.document;g.Nc=Sh&&g.E?Jc()||("CSS1Compat"==Sh.compatMode?(0,window.parseInt)(g.Lc,10):5):void 0;g.Lba=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;g.Sc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;var hd=null;"undefined"!=typeof window.XMLHttpRequest?hd=function(){return new window.XMLHttpRequest}:"undefined"!=typeof window.ActiveXObject&&(hd=function(){return new window.ActiveXObject("Microsoft.XMLHTTP")});var id={"X-YouTube-Client-Name":"INNERTUBE_CONTEXT_CLIENT_NAME","X-YouTube-Client-Version":"INNERTUBE_CONTEXT_CLIENT_VERSION","X-Youtube-Identity-Token":"XSRF_TOKEN","X-YouTube-Page-CL":"PAGE_CL","X-YouTube-Page-Label":"PAGE_BUILD_LABEL","X-YouTube-Variants-Checksum":"VARIANTS_CHECKSUM"};pd.prototype.C=function(){return{context:g.od(this.A)}};
pd.prototype.B=function(a,b,c){g.jd("//"+this.A.YO+("/youtubei/"+this.A.innertubeApiVersion+"/"+a)+"?alt=json&key="+this.A.innertubeApiKey,{headers:{"Content-Type":"application/json","X-Goog-Visitor-Id":g.v("VISITOR_DATA")},ba:b,Du:"JSON",Cc:c.Cc,X:c.X,onError:c.onError,timeout:c.timeout})};var Baa,sd;Baa={log_event:"events",log_interaction:"interactions"};g.xd={};sd={};g.wd=0;g.rd=g.p("yt.logging.transport.logsQueue_")||{};g.m("yt.logging.transport.logsQueue_",g.rd,void 0);g.h=g.Bd.prototype;g.h.clone=function(){return new g.Bd(this.x,this.y)};
g.h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};
g.h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};
g.h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.h.scale=function(a,b){var c=g.la(b)?b:a;this.x*=a;this.y*=c;return this};g.h=g.Cd.prototype;g.h.clone=function(){return new g.Cd(this.width,this.height)};
g.h.ul=function(){return this.width*this.height};
g.h.aspectRatio=function(){return this.width/this.height};
g.h.isEmpty=function(){return!this.ul()};
g.h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.h.scale=function(a,b){var c=g.la(b)?b:a;this.width*=a;this.height*=c;return this};var Caa;Caa=!g.E||g.Oc(9);g.Mba=!g.nf&&!g.E||g.E&&g.Oc(9)||g.nf&&g.Mc("1.9.1");g.Th=g.E&&!g.Mc("9");g.Nba=g.E||g.of||g.Md;g.Oba=g.E&&!g.Oc(9);var Fd={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};g.$f=g.ab("Firefox");g.Uh=g.Ic()||g.ab("iPod");g.Vh=g.ab("iPad");g.Pba=g.ab("Android")&&!(g.cb()||g.ab("Firefox")||g.ab("Opera")||g.ab("Silk"));g.Wh=g.cb();g.Xh=g.ab("Safari")&&!(g.cb()||g.ab("Coast")||g.ab("Opera")||g.ab("Edge")||g.ab("Silk")||g.ab("Android"))&&!(g.Ic()||g.ab("iPad")||g.ab("iPod"));var Xd={},Haa=0;g.Yd.prototype.Mb=g.ba(2);g.Zd.prototype.toString=function(){return this.topic};var Qba=g.p("yt.pubsub2.instance_")||new g.tb;g.tb.prototype.subscribe=g.tb.prototype.subscribe;g.tb.prototype.unsubscribeByKey=g.tb.prototype.td;g.tb.prototype.publish=g.tb.prototype.oa;g.tb.prototype.clear=g.tb.prototype.clear;g.m("yt.pubsub2.instance_",Qba,void 0);g.Yh=g.p("yt.pubsub2.subscribedKeys_")||{};g.m("yt.pubsub2.subscribedKeys_",g.Yh,void 0);g.Zh=g.p("yt.pubsub2.topicToKeys_")||{};g.m("yt.pubsub2.topicToKeys_",g.Zh,void 0);g.$h=g.p("yt.pubsub2.isAsync_")||{};
g.m("yt.pubsub2.isAsync_",g.$h,void 0);g.m("yt.pubsub2.skipSubKey_",null,void 0);var Ee=(0,g.F)().toString();var qe=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{};g.t(be,g.Yd);var Raa=new g.Zd("timing-sent",be);var Iaa=/url\(["']?(http[^'"\)]+)['"]?\)/i;var te={'script[name="scheduler/scheduler"]':"sj",'script[name="player/base"]':"pj",'link[rel="stylesheet"][name="www-player"]':"pc",'script[name="desktop_polymer/desktop_polymer"]':"dpj",'link[rel="import"][name="desktop_polymer"]':"dph",'script[name="mobile_polymer/mobile_polymer"]':"mpj",'link[rel="import"][name="mobile_polymer"]':"mph",'script[name="mobile-polymer-player/mobile-polymer-player"]':"mppj",'link[rel="stylesheet"][name="mobile-polymer-player"]':"mppc"},pe={ad_at:"ad_type",cpn:"client_playback_nonce",
csn:"client_screen_nonce",yt_lt:"load_type",yt_ad:"is_monetized",yt_ad_pr:"preroll_allowed",yt_red:"is_red_subscriber",yt_vis:"is_visible"},Oaa=["is_monetized","preroll_allowed","is_red_subscriber","is_visible"],ye=(0,g.q)(qe.clearResourceTimings||qe.webkitClearResourceTimings||qe.mozClearResourceTimings||qe.msClearResourceTimings||qe.oClearResourceTimings||g.ea,qe),je=qe.mark?(0,g.q)(qe.mark,qe):g.ea;qe.measure&&(0,g.q)(qe.measure,qe);var Ke;g.Rba=g.Md?"webkit":g.nf?"moz":g.E?"ms":g.of?"o":"";Ke=g.p("yt.dom.getNextId_");if(!Ke){Ke=function(){return++Sba};
g.m("yt.dom.getNextId_",Ke,void 0);var Sba=0};g.Ne.prototype.preventDefault=function(){this.event&&(this.event.returnValue=!1,this.event.preventDefault&&this.event.preventDefault())};
g.Ne.prototype.stopPropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopPropagation&&this.event.stopPropagation())};
g.Ne.prototype.stopImmediatePropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopImmediatePropagation&&this.event.stopImmediatePropagation())};
var Saa={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1,webkitMovementX:1,webkitMovementY:1};g.Oe=g.p("yt.events.listeners_")||{};g.m("yt.events.listeners_",g.Oe,void 0);var Qe=g.p("yt.events.counter_")||{count:0};g.m("yt.events.counter_",Qe,void 0);var Taa={enablejsapi:1},Uaa={},Vaa={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};We.prototype.clone=function(){var a=new We,b;for(b in this)if(this.hasOwnProperty(b)){var c=this[b];"object"==g.ga(c)?a[b]=g.Xa(c):a[b]=c}return a};g.Ye=null;g.cf=/\s*;\s*/;g.h=g.bf.prototype;g.h.isEnabled=function(){return window.navigator.cookieEnabled};
g.h.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');g.ca(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,g.F)()+1E3*c)).toUTCString();this.A.cookie=a+"="+b+e+d+c+f};
g.h.get=function(a,b){for(var c=a+"=",d=(this.A.cookie||"").split(g.cf),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};
g.h.remove=function(a,b,c){var d=g.ca(this.get(a));this.set(a,"",0,b,c);return d};
g.h.Kb=g.ba(3);g.h.jb=g.ba(4);g.h.isEmpty=function(){return!this.A.cookie};
g.h.ob=g.ba(0);g.h.ne=g.ba(5);g.h.clear=function(){for(var a=g.df(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
g.ef=new g.bf("undefined"==typeof window.document?null:window.document);g.ef.C=3950;g.ai=g.E?"focusin":"DOMFocusIn";g.bi=g.E?"focusout":"DOMFocusOut";g.ci=g.Md?"webkitTransitionEnd":g.of?"otransitionend":"transitionend";g.h=g.rf.prototype;g.h.getHeight=function(){return this.bottom-this.top};
g.h.clone=function(){return new g.rf(this.top,this.right,this.bottom,this.left)};
g.h.contains=function(a){return g.sf(this,a)};
g.h.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
g.h.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
g.h.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
g.h.scale=function(a,b){var c=g.la(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};g.h=g.tf.prototype;g.h.clone=function(){return new g.tf(this.left,this.top,this.width,this.height)};
g.h.contains=function(a){return a instanceof g.tf?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};
g.h.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.h.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.h.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.h.scale=function(a,b){var c=g.la(b)?b:a;this.left*=a;this.width*=a;this.top*=c;this.height*=c;return this};var uf;uf={};g.di=g.nf?"MozUserSelect":g.Md||g.Lh?"WebkitUserSelect":null;g.fa(g.Cf);g.Bf=g.p("yt.prefs.UserPrefs.prefs_")||{};g.m("yt.prefs.UserPrefs.prefs_",g.Bf,void 0);g.h=g.Cf.prototype;g.h.get=function(a,b){Ef(a);Df(a);var c=void 0!==g.Bf[a]?g.Bf[a].toString():null;return null!=c?c:b?b:""};
g.h.set=function(a,b){Ef(a);Df(a);if(null==b)throw"ExpectedNotNull";g.Bf[a]=b.toString()};
g.h.remove=function(a){Ef(a);Df(a);delete g.Bf[a]};
g.h.save=function(){var a;a=[];for(var b in g.Bf)a.push(b+"="+(0,window.escape)(g.Bf[b]));a=a.join("&");g.ff("PREF",a,63072E3)};
g.h.clear=function(){g.Bf={}};g.ei=g.Qa(function(){if(g.E)return g.Mc("10.0");var a=window.document.createElement("DIV"),b=g.qf(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");g.yc(a,g.wc("div",{style:c}));return""!=g.wf(a.firstChild,"transition")});g.fa(g.Lf);g.Lf.prototype.getVersion=function(){return[this.major,this.minor,this.A]};var Zaa=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var ig;var fi=g.$a,fi=fi.toLowerCase();if(g.xa(fi,"android")){var gi=fi.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(gi)ig=Number(gi[1]);else{var hi={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},ii=fi.match("("+g.Sa(hi).join("|")+")");ig=ii?hi[ii[0]]:0}}else ig=void 0;var bba=['video/mp4; codecs="avc1.42001E, mp4a.40.2"','video/webm; codecs="vp8.0, vorbis"'],cba=['audio/mp4; codecs="mp4a.40.2"'];g.t(g.Wf,g.pb);g.Wf.prototype.Ua=g.ba(6);g.Wf.prototype.U=function(){Yf(this);g.Wf.L.U.call(this)};var $aa={"api.invalidparam":2,auth:150,"drm.auth":150,heartbeat:150,"html5.unsupportedads":5,"fmt.noneavailable":5,"fmt.decode":5,"fmt.unplayable":5,"html5.missingapi":5,"html5.unsupportedlive":5,"drm.unavailable":5};g.t(ag,g.pb);var aba=["drm.unavailable","fmt.noneavailable","html5.missingapi","html5.unsupportedads","html5.unsupportedlive"];g.h=ag.prototype;g.h.getId=function(){return this.ga};
g.h.Bo=function(a,b){this.isDisposed()||(cg(this,a),gg(this,b),this.K&&dg(this))};
g.h.lz=function(){return this.kb};
g.h.WO=function(){if(!this.aa){var a=jg(this);a&&"html5"==lg(this)?(this.F="html5",this.K||this.Rg()):(mg(this),this.F="html5",a&&this.M?(this.D.appendChild(this.M),this.Rg()):(this.A.loaded=!0,this.R=(0,g.q)(function(){var a=this.D,c=this.A.clone();g.p("yt.player.Application.create")(a,c);this.Rg()},this),this.aa=!0,a?this.R():(g.Ec(this.A.assets.js,this.R),g.Vf(this.A.assets.css))))}};
g.h.VO=function(){var a=this.A.clone();if(!this.G){var b=fg(this);b&&(this.G=window.document.createElement("span"),this.G.tabIndex=0,Xf(this.ea,this.G,"focus",this.Dt),this.W=window.document.createElement("span"),this.W.tabIndex=0,Xf(this.ea,this.W,"focus",this.Dt),g.Rd(this.G,b),g.Sd(this.W,b))}a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==lg(this)?(this.F="flash",this.K||Uf(a,!1,(0,g.q)(this.Rg,this))):(mg(this),this.F="flash",this.A.loaded=!0,g.Tf(this.D,a),
this.Rg())};
g.h.Dt=function(){fg(this).focus()};
g.h.Rg=function(){if(!this.isDisposed()){var a=fg(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(f){}if(b)if(this.aa=!1,a.isNotServable&&a.isNotServable(this.A.args.video_id))hg(this);else{Zf(this);this.K=!0;a=fg(this);a.addEventListener&&(this.T=kg(this,a,"addEventListener"));a.removeEventListener&&(this.Qa=kg(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),c=0;c<b.length;c++){var d=b[c];this.api[d]||(this.api[d]=kg(this,
a,d))}for(var e in this.B)this.T(e,this.B[e]);dg(this);this.Wa&&this.Wa(this.api);this.Y.oa("onReady",this.api)}else this.Db=g.yb((0,g.q)(this.Rg,this),50)}};
g.h.kP=function(){return this.K};
g.h.ge=function(a,b){if(!this.isDisposed()){var c=bg(this,b);if(c){if(!g.Ja(this.Tb,a)&&!this.B[a]){var d=dba(this,a);this.T&&this.T(a,d)}this.Y.subscribe(a,c);"onReady"==a&&this.K&&g.yb(g.r(c,this.api),0)}}};
g.h.ZM=function(a,b){if(!this.isDisposed()){var c=bg(this,b);c&&this.Y.unsubscribe(a,c)}};
g.h.ny=function(a){a=a?Faa:Eaa;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||b==this.G||b==this.W||(b.focus(),b!=window.document.activeElement));)b=a(b)};
g.h.cp=function(a){g.z("a11y-announce",a)};
g.h.TI=function(a){hg(this,a)};
g.h.WI=function(a){g.z("WATCH_LATER_VIDEO_ADDED",a)};
g.h.XI=function(a){g.z("WATCH_LATER_VIDEO_REMOVED",a)};
g.h.AI=function(){this.gb||(g.Wh?(this.bb=g.Ld(window.document),Xf(this.H,window,"scroll",this.hL),Xf(this.H,this.D,"touchmove",this.KK)):(Xf(this.H,this.D,"mousewheel",this.St),Xf(this.H,this.D,"wheel",this.St)),this.gb=!0)};
g.h.BI=function(){Yf(this.H);this.gb=!1};
g.h.St=function(a){g.Se(a)};
g.h.hL=function(){window.scrollTo(this.bb.x,this.bb.y)};
g.h.KK=function(a){a.preventDefault()};
g.h.XO=function(){mg(this);this.F="unsupported";var a='Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>',b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a='Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/"> Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>');
b=this.A.messages.player_fallback||a;a=g.C("player-unavailable");g.C("unavailable-submessage")&&a&&(g.C("unavailable-submessage").innerHTML=b,(b=g.D("icon",a))&&g.Bc(b,"icon")&&(b.src=g.A(b,"icon")),g.Af(a,!0),g.I(g.C("player"),"off-screen-trigger"))};
g.h.dA=function(){return this.F||lg(this)};
g.h.Oz=function(){return this.rb};
g.h.cancel=function(){this.R&&g.Fc(this.A.assets.js,this.R);g.Ab(this.Db);this.aa=!1};
g.h.U=function(){mg(this);if(this.M&&this.A)try{this.M.destroy()}catch(b){g.Cb(b)}this.Ya=null;for(var a in this.B)g.da[this.B[a]]=null;this.kb=this.A=this.api=null;delete this.D;delete this.P;ag.L.U.call(this)};g.og={};g.ng="player_uid_"+(1E9*Math.random()>>>0);var Tba=g.p("yt.abuse.botguardInitialized")||Ze;g.m("yt.abuse.botguardInitialized",Tba,void 0);var Uba=g.p("yt.abuse.invokeBotguard")||g.$e;g.m("yt.abuse.invokeBotguard",Uba,void 0);var Vba=g.p("yt.abuse.dclkstatus.checkDclkStatus")||af;g.m("yt.abuse.dclkstatus.checkDclkStatus",Vba,void 0);var Wba=g.p("yt.player.exports.navigate")||g.mf;g.m("yt.player.exports.navigate",Wba,void 0);var Xba=g.p("yt.player.embed")||g.pg;g.m("yt.player.embed",Xba,void 0);var Yba=g.p("yt.player.getPlayerByElement")||g.qg;
g.m("yt.player.getPlayerByElement",Yba,void 0);var Zba=g.p("yt.util.activity.init")||g.Ue;g.m("yt.util.activity.init",Zba,void 0);var $ba=g.p("yt.util.activity.getTimeSinceActive")||g.Ve;g.m("yt.util.activity.getTimeSinceActive",$ba,void 0);var aca=g.p("yt.util.activity.setTimestamp")||Te;g.m("yt.util.activity.setTimestamp",aca,void 0);var tg,yg;g.xg=null;yg="";Dg.prototype.reset=function(){this.context=this.C=this.D=this.A=null;this.B=!1};
var Eg=new eb(function(){return new Dg},function(a){a.reset()},100);
g.Cg.prototype.then=function(a,b,c){return g.Og(this,g.ma(a)?a:null,g.ma(b)?b:null,c)};
g.zg(g.Cg);g.Cg.prototype.cancel=function(a){0==this.A&&mb(function(){var b=new Ng(a);Ig(this,b)},this)};
g.Cg.prototype.W=function(a){this.A=0;g.Bg(this,2,a)};
g.Cg.prototype.H=function(a){this.A=0;g.Bg(this,3,a)};
g.Cg.prototype.P=function(){for(var a;a=Jg(this);)Kg(this,a,this.A,this.K);this.G=!1};
var Qg=db;g.t(Ng,g.ra);Ng.prototype.name="cancel";var Rg={},Tg=[],Sg=0;var Vg=null,Yg=[];var bh,sh,rh,dh,ch,vba,oba,rba,pba,qba,nh;dh=0;ch=0;vba=["server_prefetched_vast","vmap"];oba=[900,60,"waiting"];rba=[500,99,"waiting"];pba=[300,60,"waiting"];qba=[400,99,"waiting"];nh=[300,101,"done"];window.yt=window.yt||{};g.m("yt.setConfig",g.wb,void 0);g.m("yt.pushConfigArray",function(a,b){var c=g.v(a,void 0);c?c.push(b):g.wb(a,[b])},void 0);
g.m("yt.getConfig",g.v,void 0);g.m("yt.hasMsg",g.Eb,void 0);g.m("yt.pubsub.publish",g.z,void 0);g.m("yt.pubsub.subscribe",g.x,void 0);g.m("yt.setMsg",function(a){ub(g.Db,arguments)},void 0);
g.m("yt.setGoogMsg",function(a){ub(g.Db,arguments)},void 0);
g.m("yt.timing.reportAdToVideo",function(a,b,c,d){c={v:2,s:c?"youtube_mobile":"youtube",action:d?"watch,ad2video_html5":"watch,ad2video"};a.aft=a.pbs=a.astv||a.actv;d=[];for(var e in a)"_"!=e.charAt(0)&&d.push(e+"."+Math.round(a[e]));c.rt=d.join(",");for(var f in b)"_"!=f.charAt(0)&&(c[f]=b[f]);a=g.v("TIMING_INFO",{});"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);we(c,!1)},void 0);
g.m("ytcsi.tick",g.le,void 0);g.t(uh,g.Tb);
uh.prototype.enable=function(){window.onload=mba;window.onunload=nba;window.onerror=naa;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfclick",$g),window.addEventListener("spfhistory",ah),window.addEventListener("spfrequest",fh),window.addEventListener("spfpartprocess",jh),window.addEventListener("spfpartdone",kh),window.addEventListener("spfprocess",lh),window.addEventListener("spfdone",oh),window.addEventListener("spferror",ph),window.addEventListener("spfreload",
qh),window.addEventListener("spfjsbeforeunload",vh)),a.config=a.config||{},window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",tba),this.subscribe("dispose",uba)):window.spf.dispose();
this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
uh.prototype.init=function(){uh.L.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&g.v("PAGEFRAME_JS")?(b=g.v("PAGEFRAME_JS",void 0),c=function(){window.ytPageFrameLoaded=!0;g.p("ytbin.www.pageframe.setup")()}):a&&(a=g.p("yt.www.masthead.loadSearchbox"))&&a();
var a=g.v("JS_COMMON_MODULE"),d=g.v("JS_PAGE_MODULES");d||(d=[a]);a=g.v("JS_DELAY_LOAD",0);0<a?(g.Ab(this.B),this.B=g.yb(function(){b&&g.Ec(b,c);window.spf.script.require(d)},a)):(b&&g.Ec(b,c),window.spf.script.require(d));
fba();Qaa();Naa();De(!0);ke(!1);"serviceWorker"in window.navigator&&"https:"==window.location.protocol&&(g.Gc("service_worker_enabled")?wba():window.navigator.serviceWorker.controller&&window.navigator.serviceWorker.getRegistration().then(yba))};
uh.prototype.dispose=function(){g.Ab(this.B);var a=g.p("ytbin.www.pageframe.cancelSetup");a&&a();g.Bb(tg);if(a=g.vg())a.removeEventListener("onReady",ug),a.removeEventListener("onStateChange",ug);De(!1);uh.L.dispose.call(this)};
uh.prototype.disable=function(){uh.L.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfclick",$g),window.removeEventListener("spfhistory",ah),window.removeEventListener("spfrequest",fh),window.removeEventListener("spfpartprocess",jh),window.removeEventListener("spfpartdone",kh),window.removeEventListener("spfprocess",lh),window.removeEventListener("spfdone",oh),window.removeEventListener("spferror",ph),window.removeEventListener("spfreload",qh),window.removeEventListener("spfjsbeforeunload",
vh));window.onload=null;window.onunload=null;window.onerror=null};
g.Yb(new uh);})(_yt_www);
